### ISSUE TITLE
Conso CPU élevée

### ISSUE THREAD

**Issue by Marc--** [NextDom/plugin-teleinfo#101]
Bonjour ticed !

Je constate une consommation CPU élevée sur mon serveur Jeedom. En cherchant un peu, c'est le process mysqld qui est gourmand.

Un "show full processlist" m'a montré que c'est lié au plugin téléinfo:
Récupération de l'id dans le process
select * from cmd WHERE id=<id recupéré>;

--> | 704874 |        122 | virtual | NULL      |     3 | **Prod instant** | {"calcul":"#704709#","returnStateValue":"","returnStateTime":"","minValue":"0","maxValue":"3000"} | []       | 1            | info | numeric |       | {"invertBinary":"0","groupingType":"","graphType":"line"} |         1 | #704709# | []   | []    | NULL         |

On voit "Prod instant" dans la colonne "name". Je suis donc quasi sur que c'est téléinfo ! (n'hésite pas si je dis des bêtises).

Pour confirmer, j'ai stoppé le démon... et la conso chute. Je te laisse apprécier les graphiques, pas besoin de te dire quand j'ai stoppé le plugin. Ce qui est surprenant, c'est la montée en charge depuis un mois. Ceci dit s'il effectue des opérations sur les données historisées, vu qu'il y en a de plus en plus c'est logique.

![2019-05-16 09_58_04-Dashboard - Jeedom](https://user-images.githubusercontent.com/9568739/57837531-49ae5280-77c3-11e9-8181-5f4f43f5f9fe.png)

![2019-05-16 09_58_24-Dashboard - Jeedom](https://user-images.githubusercontent.com/9568739/57837550-4f0b9d00-77c3-11e9-9993-19316152787e.png)

## Environnement
* **Version Jeedom**: 3.3.24
* **Platform**: DIY Debian 9
* **Version du Plugin (ex: 4.2.0)**: 4.5.1
* **Type de modem**: Modules téléinfo DIY USB
* **Compteur linky**:  Oui, conso et production
* **Compteur standard ou historique**: Standard (les deux)

## Le package diagnostic:
[teleinfolog.zip](https://github.com/NextDom/plugin-teleinfo/files/3185959/teleinfolog.zip)

Je suis à dispo pour du debug dans la limite des mes compétences !

**Comment by ticed35** [comment]
Salut @Marc-,
N'as tu pas plutôt un virtuel qui se met à jour sur certaines valeurs envoyé sur le plugin teleinfo ? Car je vois plutôt qu'il s'agirait de ton virtuel nommé Prod Instant.

**Comment by Marc--** [comment]
Hummm en effet, j'ai créé deux virtuels car je ne trouvais pas un moyen d'afficher simplement mes index et la conso instantanée sur le dashboard.

Donc je viens de les virer, et j'ai redémarré le démon. Malheureusement j'ai de nouveau une forte conso.


Peux tu me donner une méthode pour repartir de zéro avec le plugin ? Si je le désinstalle, cela va-t-il virer toutes les entrées dans la base ? Car je constate aussi que je n'ai pas les statistiques... je voudrais repartir de zéro et voir si c'est mieux plutôt que chercher sur une install qui a déjà du vécu.

**Comment by ticed35** [comment]
Normalement en supprimant l'objet puis réinstallant le plugin tu devrais repartir de zero. 
Il me semble que jeedom s'occupe de tout bien supprimer lors de la suppression de l'objet.

**Comment by Marc--** [comment]
Ok je test ça alors. 

Car je pense avoir un soucis. On voit bien la période de coupure du plugin sur la conso CPU de mon PC.  Ce n'est pas un foudre de guerre, mais ça reste récent (i3-6100T @ 3.20GHz)

![2019-05-16 13_53_58-Dashboard - Jeedom](https://user-images.githubusercontent.com/9568739/57852478-9570f400-77e3-11e9-8bda-37422b19c8e3.png)

**Comment by ticed35** [comment]
Ce que tu peux faire également c'est mettre un délai de lecture plus long afin de réduire la charge. Il est possible que tes compteurs parlent beaucoup.
Dans les options du plugin, configuration avancée change la valeur de Cycle sommeil acquisition teleinfo par 5 secondes par exemple.

**Comment by Marc--** [comment]
Je suis passé à 1s pour l'instant, soit le double de la valeur par défaut. La charge à déjà bien chuté suite à la suppression et réinstallation du plugin. Et j'ai l'impression que les stats sont OK. Mais j'attend 24h pour être sur.

Par contre je ne suis pas sur que ce soit uniquement lié aux virtuels. A surveiller de mon côté.
![2019-05-16 21_22_04-Window](https://user-images.githubusercontent.com/9568739/57881536-d25bdb80-7821-11e9-9769-5a5df964f44d.png)

Merci pour ta réactivité !

**Comment by ticed35** [comment]
D'ac, à surveiller.
Je ferme en attendant. Réouvre si c'est problématique.
Si tu rencontre des soucis tu peux même passer facilement à 2 secondes cela n'impactera pas.
