### ISSUE TITLE
Erreur de typo sur la valeur SINSTI

### ISSUE THREAD

**Issue by arly69** [NextDom/plugin-teleinfo#102]
## Description
Bonjour, une erreur de typo se trouve dans la documentation ENEDIS sur la variable SINSTI qui en fait est transmise sous le label SINST1 (le chiffre 1 et non le i majuscule). En corrigeant dans les fichiers du plugin on obtient un comportement normal pour cette valeur qui sert aux statistiques.
J'ai un Linky en mode Standard et un module NodeMCU avec Wifinfo v2 (que j'ai moi-même retravaillé pour le mode Standard du linky et l'appel en POST de votre plugin)

## Environnement
* **Version Jeedom**: 3.3.24
* **Platform**: Debian
* **Version du Plugin (ex: 4.2.0)**: last stable 2019-05-15 01:58:00
* **Type de modem**: aucun
* **Compteur linky**: Linky 
* **Compteur standard ou historique**: Standard
Pas de deamon, transmission depuis le Wifinfo en requête POST sous format json

**Comment by Jef-73** [comment]
Il faudrait faire marche arrière car soit c'était une erreur de lecture à l'époque, soit Enedis a corrigé cela depuis (mais je n'ai pas trouvé d'info là-dessus sur le net).
Voir le dossier d'incident #112 si besoin  ;-)
