### ISSUE TITLE
Problème teleinfo avec modem 2 compterurs et linky

### ISSUE THREAD

**Issue by cdalcorso** [NextDom/plugin-teleinfo#107]
Bonjour,

J'ai un problème de remonté d'informations du plugin teleinfo avec le modem USB 2 compteurs Carteletronic et 2 compteurs linky ( consomation et production )

Mon installation comporte 2 compteurs linky, un de consommation en mode historique et l'autre de production en mode standard.

Je suis sous Raspbian GNU/Linux 9 (stretch) avec Jeedom version 3.3.29 et le plugin teleinfo version 4.6.1

Ma configuration est :
Port du modem 1 : le port usb disparait après la sélection et le démarrage du deamon
Modem 2 compteurs (Cartelectronic) : coché
Compteur 1 Type Linky : coché
Compteur 1 vitesse : 1200
Compteur 2 Type Linky : coché
Compteur 2 vitesse : 9600

Le Diagnostique donne :
Etape 1 : Modem configuré :
Etape 2 : Accès KO
Etape 3 : OK
Etape 4 : NOK
Etape 5 : OK

Je vous joint le fichier teleinfo_deamon_conso
[teleinfo_deamon_conso.txt](https://github.com/NextDom/plugin-teleinfo/files/3544383/teleinfo_deamon_conso.txt)

J'ai donc les informations du compteur de consommation mais pas celles du compteur de production.
J'ai testé avec l'application windows de Cartelectronic TELEINFO 43J j et je récupéré

 bien toutes les informations
Pourriez-vous s'il vous plaît m'aider à résoudre ce problème.
Merci d'avance et bonne journée

Amicalement
Christian

**Comment by slobberbone** [comment]
@ticed35 aurais-tu une piste ?

**Comment by ticed35** [comment]
Salut, 
Le modem 2 compteur ne peut pas être utilisé sous 2 modes en même temps c'est pour cela. 
Il faut soit 2 modem soit 2 compteurs sous le même mode de fonctionnement.

**Comment by cdalcorso** [comment]
Bonjour,

Merci beaucoup pour cette réponse
