### ISSUE TITLE
Perte de 50 % des trames

### ISSUE THREAD

**Issue by Ambass** [NextDom/plugin-teleinfo#108]
Bonjour,
J'utilise ce plugin depuis des années pour faire du délestage en cas de dépassement de la puissance souscrite. ( Compteur traditionnel )
Le plugin perd une trame sur deux depuis toujours.... de ce fait l'info IINST peut arriver un peu tard.
L'information revient actuellement toutes les 3 secondes au lieu de 1.5 environ.
J'avais fait la modif il y a fort longtemps, mais à chaque mise à jour elle est perdue....
Donc je joins le fichier modifié , comme cela, tout le monde pourra en profiter.

[teleinfo.zip](https://github.com/NextDom/plugin-teleinfo/files/3586401/teleinfo.zip)

**Comment by slobberbone** [comment]
Salut merci pour le retour !
Veux-tu proposer ta modificatione n Pull Request ? @Ambass

**Comment by ticed35** [comment]
Ne pouvant valider car je n'ai plus de téléinfo peux-tu comme slobberbone a dit proposer ta modification en pull request beta afin de voir ce qui pose souci et faire valider par des utilisateurs. 
Merci
@Ambass

**Comment by Ambass** [comment]
Salut, 
Désolé pour le retour tardif, j'étais loin de tout cela depuis 3 semaines.
Ceci dit, je n'ai jamais utilisé Git... ( seulement SVN ! ) et je n'ai pas trop le temps de m'investir la dedans...
Si vous pouviez le faire à partir du fichier joint, ça serait sympa.
Merci.

**Comment by ticed35** [comment]
Salut, malheureusement dans ce cas cela restera comme cela. Je ne peux pas tester les modifications, il y a trop de risque de ne plus rien recevoir.
