### ISSUE TITLE
Compatibilité php 7.3

### ISSUE THREAD

**Issue by jmvedrine** [NextDom/plugin-teleinfo#109]
Bonjour,
il reste une ligne avec la class object qui pose problème en php 7.3
C'est dans le fichier teleinfo\desktop\php\teleinfo.php
foreach (object::all() as $object) {
devrait être
foreach (jeeObject::all() as $object) {
Je n'utilise pas le plugin car je n'ai pas de modem téléinfo, mais j'ai vu les messages d'utilisateurs dans le forum Jeedom, et j'ai jeté un oeil au code, j'ai vu que la modif avait bien été faite partout sauf là.
Amicalement.
Jean-Michel

**Comment by ticed35** [comment]
Salut Jean-Michel, 
Merci ! Je vais pousser la modification.
