### ISSUE TITLE
Demon ne démarre plus après Update 4.6.2 et core 3.3.31

### ISSUE THREAD

**Issue by rgtintin** [NextDom/plugin-teleinfo#110]
## Description
Le démon ne démarre plus depuis que j'ai fait un Update du core de 3.3.30 vers 3.3.31 et du plugin vers 4.6.2.
J'ai refait la configuration, relancé les dépendances, mais rien n'y fait.
Dans le log du démon il y a: [ERROR] : Callback result as a unknown error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661). Please check your network configuration page

## Etapes à reproduire (pour les bugs)
1. faire un update du core et du plugin

2.
3.
4.

## Environnement
* **Version Jeedom**: 3.3.31
* **Platform**: Jeedom Smart
* **Version du Plugin (ex: 4.2.0)**: 4.6.2
* **Type de modem**: Cartelectronic USB 1 TIC
* **Compteur linky**: oui mais en mode historique
* **Compteur standard ou historique**: historique

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.
Le package est au format tar, qui n'est pas supporté par Github, je l'ai remplacé par un Zip
[teleinfolog.zip](https://github.com/NextDom/plugin-teleinfo/files/3638513/teleinfolog.zip)

**Comment by ticed35** [comment]
Salut, 
Ta configuration en local est réglé sur https. 
=> [2019-09-21 08:40:09][INFO] : GLOBAL------Callback : https://127.0.0.1:80/plugins/teleinfo/core/php/jeeTeleinfo.php

Il faut que le réglage network local soit sur http pour que cela fonctionne.

**Comment by rgtintin** [comment]
Super! Merci, cela a résolu mon problème !Ce que je ne comprends pas c'est que mettre le réseau local en https, pour sécuriser l'accès, ai une influence sur un module interne...Mais comme je n'ai pas besoin du https en local, ce n'ai pas un problème.Merci encore !Romuald

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 23, 2019 à 18:05, Cédric<notifications@github.com> a écrit :   
Salut,
Ta configuration en local est réglé sur https.
=> [2019-09-21 08:40:09][INFO] : GLOBAL------Callback : https://127.0.0.1:80/plugins/teleinfo/core/php/jeeTeleinfo.php

Il faut que le réglage network local soit sur http pour que cela fonctionne.

**Comment by ticed35** [comment]
C'est parce que Jeedom communique ce qui est configuré dans la page réseau pour le callback des plugins. 
En saisissant https le démon va vouloir utiliser https. Cela peut fonctionner en ajoutant le certificat utilisé en tant que certificat de confiance mais cela réduira les performances.
