### ISSUE TITLE
Linky mode standard : widget OK, affichages manquants sur panneau desktop

### ISSUE THREAD

**Issue by berniland** [NextDom/plugin-teleinfo#111]
Bonjour, petit soucis sur les stats du panneau desktop
## Environnement
* **Version Jeedom**: 3.3.34
* **Platform**: raspberry 3
* **Version du Plugin 6.4.2
* **Type de modem**: cartelectronic USB TIC
* **Compteur linky**
* **Compteur standard **
## Contexte
-->le widget fonctionne ( il manque 2 noms mais pas grave, pas encore trouvé ou modifier)
![image](https://user-images.githubusercontent.com/48030185/67326761-41e39e80-f517-11e9-8a44-878c849ca985.png)
sachant que je suis en mode standard:
-puissance instantanée = commande PINST / affiché / histo
-index HC                      = commande Index HC / affiché / histo
-index HP                      = commande Index HP / affiché / histo
-Puissance max du jour= commande P MAX   / affiché / histo
-conso total HC+HP  = commande EAST / affiché / histo
-conso HC du jour         = commande STAT_TODAY_HC / histo
-conso HP du jour         = commande STAT_TODAY_HP / histo
-conso total hier            = commande STAT_YESTERDAY / histo
-conso HC hier              = commande STAT_YESTERDAY_HC / histo
-conso HP hier              = commande STAT_YESTERDAY_HP / histo
-->panneau desktop:
------> Ma consommation: fonctionne mais je ne peux pas convertir en €
![image](https://user-images.githubusercontent.com/48030185/67328260-82dcb280-f519-11e9-9c0e-51852c4d20c4.png)
------> Puissance: rien
------> Evoluion journalière: ça fonctionne, il se base sur la commande STATS YESTERDAY. y a t il la possiblité de changer ? par exemple mettre HC/HP (comme evo mensuelle)? n'y a t il pas une journée de décallage si on se base sur la commande YESTERDAY  et le graphe est fait la nuit ? .. Si les stats sont justes c'est le principal :)
![image](https://user-images.githubusercontent.com/48030185/67328759-3b0a5b00-f51a-11e9-87c4-401c2db0fb37.png)
------> Evoluion Mensuelle : OK
Ma question est peut on entrer facilement dans les paramtres du panneau ? ou comment troubleshooter ou vous envoyer les bons fichiers et logs pour m'aider a corriger? 
 Merci pas avance pour votre réponse
bonne soirée
berni

Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by Jef-73** [comment]
Bonjour,
Moi aussi sur un compteur Linky en mode "standard" (et pas "historique") il me manque l'affichage d'une valeur au-dessus de la jauge : la "SINSTS".

**Comment by berniland** [comment]
bonjour,
en efffet le graphique puissance montre la variable PAPP au lieu de PINST en mode standard
![image](https://user-images.githubusercontent.com/48030185/67622575-b53d2700-f81b-11e9-88e3-d12bf4afe726.png)
 et si le PINST ou juste puissance instantanée pouvait s'afficher dans le widget.
merci bonne journée

**Comment by ticed35** [comment]
Bonjour, pour le nom de la valeur qui ne s'affiche pas j'ai du faire une erreur au moment de la création de la commande, je vais checker cela. 

Pour le problème d'affichage de la valeur en euro est-ce que vous pouvez vérifier que vous avez renseigné des valeur dans la zone option du plugin ? Si celles-ci sont à 0 cela n'affichera rien. 

@berniland, est-ce que tu as une valeur pour "Votre abonnement" sur ton objet compteur ?

**Comment by Jef-73** [comment]
Bonjour,
Tant que tu y es à corriger les noms qui ne s'affichent pas, voici les deux que j'ai trouvés :

1) sur un compteur Linky en mode "standard" il me manque l'affichage du nom d'une valeur au-dessus de la jauge : la "SINSTS". Seule la jauge et la valeur s'affichent.

2) sur un compteur Linky en mode "historique" l'affichage du nom de la valeur au-dessus de la jauge "PAPP" ne s'affiche pas, j'ai "</i>" à la place (inférieur + slash + lettre i + supérieur).

Merci :)

**Comment by ticed35** [comment]
> bonjour,
> en efffet le graphique puissance montre la variable PAPP au lieu de PINST en mode standard
> ![image](https://user-images.githubusercontent.com/48030185/67622575-b53d2700-f81b-11e9-88e3-d12bf4afe726.png)
> et si le PINST ou juste puissance instantanée pouvait s'afficher dans le widget.
> merci bonne journée

Tu veux pas dire plutôt SINSTS au lieu de PINST ?

@Jef-73, en effet les 2 étaient configurées pour avoir le display de modifié.

**Comment by Jef-73** [comment]
J'ai été voir et j'ai supprimé les icônes qui étaient paramétrées d'office : l'affichage est maintenant OK.

**Comment by berniland** [comment]
Bonsoir Cedric,
 c'es mieux quand on met les prix au Kwh  :) je n'avais pas vu cette option.
merci
 sinon mon objet compteur affiche "H PLEINE/CREUSE"

**Comment by berniland** [comment]
POur ce qui est de la valeur SINSTS au lieu de PINST, je sais juste que c'est la puissance instantanée et que j'ai dans les commande P INST mais pas S INSTS, mais la je te fais confiance.
pour le correctif affichage SINSTS / PAPP, faut il attendre une maj ou essayer de remplacer le fichier " teleinfo.class.... ?

**Comment by ticed35** [comment]
Ça va passer dans la mise à jour de cette nuit. 
Il faut être sur la beta pour l'instant pour avoir la correction (version 4.6.5)

**Comment by Anthony-55** [comment]
Je suis en version 4.6.5 et j'ai toujours le problème d'affichage sur le nom de la PAPP
<a href='https://www.casimages.com/i/191029081547262006.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2019/10/29/191029081547262006.png' border='0' alt='Mon image' /></a>

De plus, je ne sait pas si ça a déjà été demandé mais est il possible de renseigner le tarif des heures creuse et pleinne pour un abonnement tempo ? (6 tarifs à renseigner)

**Comment by Jef-73** [comment]
Allez voir sur les paramètres avancés de la valeur PAPP et supprimez l'icône mise par défaut (il suffit de cliquer dessus). Puis sauvegardez et retournez voir le widget : le nom sera revenu :)

**Comment by ticed35** [comment]
La correction n'est valide que pour les moments ou la commande n'existe pas. Dans le cas ou elle existe il faut effectuer la manipulation de @Jef-73.
Pour les tarifs ce n'est qu'une indication. Tu as la possibilité de dire au plugin ce qu'il doit considérer comme heure pleine et ce qu'il doit considérer comme heure creuse. Il n'a pas la prétention de faire un calcul plus poussé. Pour cela il existe d'autres plugins. 

@berniland, tout est ok ou il manque des points à voir ?

**Comment by berniland** [comment]
Bonjour Cédric, c'est ok pour l'affichage dans le widget:
[image: image.png]
j'ai mon PINST.
Par contre sur le dashboard teleinfo la puissance c'est vide, je dirais
c'est normal car il va chercher la commande PAPP:
c'est étonnant car quand je clic sur teleinfo il affiche d'abord la legende
avec P INST et une second après PAPP
(je n'ai pas le temps de faire un screenshot pour te montrer)
[image: image.png]
je suis version 4.6.4


   Berni

**Comment by ticed35** [comment]
Ça me parle un peu ce que tu me dis. Une histoire entre le type du compteur. 
Peux-tu ouvrir la console de ton navigateur (touche F12) puis me montrer ce qui s'affiche lorsque tu recharges le dashboard.

**Comment by berniland** [comment]
Bonjour Cedric, voici le resultat de la console :
[loadData] Objet téléinfo récupéré : 77
VM478:97 [loadData] => Compteur Elec
VM478:189 [loadData][STAT_TODAY] 1629
VM478:183 [loadData][PAPP] 587
VM478:238 [getObjectHistory] Récupération de l'historique pour la commande
P INST
VM478:334 [getMonthlyHistory] Récupération de l'historique pour la commande
STAT_YESTERDAY_HP
VM478:334 [getMonthlyHistory] Récupération de l'historique pour la commande
STAT_YESTERDAY_HC
VM478:139 [loadData][STAT_YESTERDAY] 1166
VM478:265 [getDailyHistory] Récupération de l'historique pour la commande
STAT_YESTERDAY
VM478:183 [loadData][PAPP] 812
VM478:238 [getObjectHistory] Récupération de l'historique pour la commande
PAPP
VM478:224 [loadData] => Compteur Elec
VM478:423 [getCommandHistoryValue] monthLastYearPartial | from : 2018-10-01
00:00:00 | to : 2018-10-31 23:59:59 | value : 0
VM478:423 [getCommandHistoryValue] monthLastYear | from : 2018-10-01
00:00:00 | to : 2018-10-31 23:59:59 | value : 0
VM478:423 [getCommandHistoryValue] yearLastYear | from : 2018-01-01
00:00:00 | to : 2018-12-31 23:59:59 | value : 537.796
VM478:423 [getCommandHistoryValue] month | from : 2019-10-01 00:00:00 | to
: 2019-10-31 23:59:59 | value : 142.174
VM478:423 [getCommandHistoryValue] yearLastYearPartial | from : 2018-01-01
00:00:00 | to : 2018-10-31 23:59:59 | value : 0
VM478:423 [getCommandHistoryValue] yesterday | from : 2019-10-30 00:00:00 |
to : 2019-10-30 23:59:59 | value : 7.695
VM478:299 [getDailyHistory] Id température exterieure : 208
VM478:423 [getCommandHistoryValue] year | from : 2019-01-01 00:00:00 | to :
2019-12-31 23:59:59 | value : 4631.305
VM478:483 [getCommandHistoryCout] day coutHP : 0.366 * 0.1194
VM478:483 [getCommandHistoryCout] day coutHC : 1.263 * 0.08436
VM478:488 [getCommandHistoryCout] monthLastYear coutHP : 0 * 0.1194
VM478:488 [getCommandHistoryCout] month coutHP : 83.177 * 0.1194
VM478:488 [getCommandHistoryCout] yearLastYear coutHP : 325.433 * 0.1194
VM478:488 [getCommandHistoryCout] year coutHP : 1281.584 * 0.1194
VM478:488 [getCommandHistoryCout] yesterday coutHP : 4.25 * 0.1194
VM478:488 [getCommandHistoryCout] month coutHC : 58.997 * 0.08436
VM478:488 [getCommandHistoryCout] monthLastYear coutHC : 0 * 0.08436
VM478:488 [getCommandHistoryCout] year coutHC : 3349.721 * 0.08436
VM478:488 [getCommandHistoryCout] yearLastYear coutHC : 212.363 * 0.08436
VM478:488 [getCommandHistoryCout] yesterday coutHC : 3.445 * 0.08436

bonne journée


   Berni

**Comment by ticed35** [comment]
Salut, 
j'ai vu qu'il y a plusieurs commandes de puissance instantanée pour le même objet. 
Il ne faut en garder qu'une pour que ça s'affiche. 
Par exemple je vois PAPP et PINST qui ont la même finalité

**Comment by berniland** [comment]
j'ai verifié côté commandes je n'ai que PINST de coché et PAPP désactivé en
historique et affichage
[image: image.png]
[image: image.png]
pouvez vous m'indiquer ou changer ces commandes pour le dashboard ?
merci



   Berni

**Comment by ticed35** [comment]
Je ne vois pas tes images mais il ne faut pas déclarer plusieurs commandes de type puissance sur l'objet. 
![image](https://user-images.githubusercontent.com/13416516/68214060-bc49ff00-ffaa-11e9-8b28-5ece9499c305.png)

Il faut une seule de ces types de commandes : 
- Puissance app. Instantanée injectée (SINSTI)
- Puissance app. Instantanée injectée (SINST1)
- Puissance apparente
- Puissance app. Instantanée soutirée

Même désactivé ce n'est pas bon.

**Comment by berniland** [comment]
Oui j'ai supprimé la commande et c'est bon. Je n'ai pas encore de zoom
dispo ( J S M A sont grisés) peut être dois je attendre un peu... Ce qui
est bizarre car tous les zoom de la puissance sont dispos et fonctionnels a
partir du widget.
Une idée ?. Merci en tout cas d'avoir redonné vie a teleinfo 😊

**Comment by ticed35** [comment]
Parfait, 
Si c'est une nouvelle commande oui il faut lui laisser le temps d'acquérir des données.

**Comment by Jef-73** [comment]
Pour ma part j'ai SINSTI (injection photovoltaïque) et SINSTS (sous-tirage) en même temps et ça fonctionne. A mon sens c'est normal puisque ces deux données sont différentes.

Par contre je suis d'accord pour les trois premières ensemble, c'est en principe la même chose.

**Comment by berniland** [comment]
ce n'est pas une nouvelle commande ... voici le comparatif entre le
graphique puissance du dashboard :
[image: image.png]
et du widget :
[image: image.png]
si c'est la même commande, je devrait pouvoir changer le zoom a partir du
dashboard aussi ?
et le label ( commande je suppose )est bien le même dans les 2 :
[image: image.png]



   Berni

**Comment by Jef-73** [comment]
Bonjour berniland,
On ne voit pas les images que vous mettez dans vos posts :(

**Comment by berniland** [comment]
Bonsoir Cedric, désolé pour les images, vous devriez les voir maintenant.
Donc, après quelques semaines, je pensais que l'historique m'aurait permis de zoomer 
le graphique puissance du dashboard mais non, je n'ai que le H de dispo:
![image](https://user-images.githubusercontent.com/48030185/69281163-1de3ad80-0be8-11ea-945f-9dc5a008839b.png)
Alors que le widget me le permet et c'est la même commande P INST....
![image](https://user-images.githubusercontent.com/48030185/69281301-55525a00-0be8-11ea-9f1c-d2bc2dfb84c1.png)

Dites moi ce dont vous avez besoin pour troubleshooter .
merci bonne soirée

**Comment by ticed35** [comment]
Bonjour @berniland, je viens de percuter pour la puissance sur le panel. C'est tout à fait normal ^^
De base le panel ne charge la puissance que sur le dernier jour afin d'économiser de la puissance, ça fait beaucoup de données. 
Tu devrais pouvoir avoir plus d'infos en sélectionnant un interval en haut puis ok. 
Rien qu'en faisant ok cela chargera sur le dernier mois, je déconseille cependant car c'est beaucoup de données.
