### ISSUE TITLE
Perte remontée SINSTI dès que modif équipement

### ISSUE THREAD

**Issue by Jef-73** [NextDom/plugin-teleinfo#112]
Bonjour,

J'ai un problème qui **semble** similaire au cas #105 

## Description
Je n'ai plus d'enregistrement de la valeur SINSTI dès que je modifie l'équipement compteur et ce quelle que soit la modification faite.

## Etapes à reproduire (pour les bugs)
1. Je crée l'équipement compteur manuellement, ou automatiquement via le daemon et je ne touche à rien dans l'équipement.
2. Tout fonctionne bien.
3. Je modifie quelque chose dans l'équipement, par exemple je met l'unité à "VA" sur SINSTI, ou je masque l'affichage de données qui ne servent pas, ou je décoche l'historisation de certaines données.
4. Je sauvegarde l'équipement.
5. La valeur SINSTI reste figée sur la dernière reçue MAIS UNIQUEMENT POUR LE COMPTEUR DE PRODUCTION (donc en mode "standard"). Le compteur de conso (en mode historique) fonctionne bien lui.

Nota : j'ai toujours les valeurs SINSTI qui remontent dans le log correspondant (teleinfo_daemon_prod) avec les autres données et elles varient bien toutes.

J'ai tenté de : 
- supprimer le plugin et le réinstaller : l'équipement refonctionne, jusqu'à ce que je fasse à nouveau une modif
- supprimer l'équipement et le recréer : même problème
- supprimer la donnée SINSTI dans l'équipement et la recréer : même problème dès que modif quelconque
- créer manuellement la donnée SINSTI : même problème également

## Contexte
1 compteur de consommation : Linky en mode "historique"
1 compteur de production : Linky en mode "standard"
2 modules USB "TéléInfoStick v3", un sur chaque compteur
J'ai aussi testé avec un module de GCE sur le compteur de prod : même problème.

## Environnement
* **Version Jeedom**: 3.3.21 Stable
[teleinfo_deamon_prod.zip](https://github.com/NextDom/plugin-teleinfo/files/3774870/teleinfo_deamon_prod.zip)
[teleinfolog.zip](https://github.com/NextDom/plugin-teleinfo/files/3774871/teleinfolog.zip)

* **Platform**: R.Pi 3B+
* **Version du Plugin (ex: 4.2.0)**: 4.6.2 Stable (2019-10-23 21:31:25)
* **Type de modem**: TéléInfoStick V3 en USB (et testé aussi avec un GCE USB)
* **Compteur linky**: Sagem S12 C5
* **Compteur standard ou historique**: historique sur conso + standard sur prod 

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.
=> j'ai joint les deux, mais le diag ne semble pouvoir se faire que sur le premier modem, hors mon modem de prod est le second.

**Comment by Jef-73** [comment]
En relisant mieux le cas 105, ce n'est pas la même chose car dans le 105 il n'y a pas de remontée du tout de la valeur dans les trames, alors que moi elles sont là en permanence, c'est juste le plugin TéléInfo qui cesse de les enregistrer dès que je modifie quelque chose dans l'équipement compteur de Jeedom.

**Comment by Jef-73** [comment]
Peut-être une piste : quand je farfouille dans les fichiers et que je cherche "SINST**I**" (avec la lettre "i" majuscule à la fin), je ne trouve pas cette info.
Par contre, je trouve à la place "SINST**1**" (avec le chiffre "1" à la fin).

Est-ce que ça n'expliquerai pas ce bug des fois ?

**Comment by Jef-73** [comment]
C'est dimanche, je dois être le seul derrière mon écran à triturer Jeedom, donc je continue mon monologue :-)

Je pense avoir mis le doigt sur le problème : la correction de l'issue #102  qui portait justement sur SINSTI. Il a été demandé de remplacer "SINSTI" par "SINST1" car c'est ce que remontait le compteur Linky. Donc soit c'était une erreur, soit ça a été corrigé depuis (je n'ai rien trouvé sur le net parlant de cette modification d'Enedis, mais pourquoi pas ...).

Je confirme que le compteur Linky renvoie bien "SINSTI" (avec un i majuscule) dans ses trames. Pour preuve, voici une ligne de log actuel :
🔢 **[2019-10-26 13:47:40][DEBUG] : TELEINFO------name : SINSTI value : 00460 checksum : F** 🔢 

_Du coup, serait-il possible SVP de corriger le plugin pour qu'il prenne bien en compte "SINSTI" ?_

Par contre je n'ai aucune idée de si c'est en rapport ou pas avec mon bug de freeze de la valeur SINSTI justement ...

**Comment by Jef-73** [comment]
Confirmation : j'ai modifié les 3 fichier qu'on trouve dans le case #102 pour remettre "SINSTI" (avec un i) et je peux maintenant faire toutes les modif que je veux sans problème ni freeze de la valeur, donc c'était bien le problème  👍

**Comment by arly69** [comment]
Bonsoir,
C'est moi qui avait demandé la correction car mon compteur Linky en mode standard renvoie SINST1 (le chiffre et non le i majuscule) et c'est toujours le cas à l'heure ou j'écris. Je pense donc que le linky a peut-être été mis à jour pour vous pour corriger cette erreur. 
Il faut donc que le plugin prenne en compte ces 2 labels pour rester compatible

**Comment by Jef-73** [comment]
Bonsoir arly69,
Merci pour votre retour très intéressant : ça veut dire que quand Enedys (ou Sagem ?) corrigent une série de compteurs, ils ne prennent même pas la peine d'envoyer les corrections sur les anciens 👎

**Comment by ticed35** [comment]
Salut, 
Ce qui est étonnant c'est que pour la correction je suis reparti de la notice de spécification erdf donc on ne devrait pas avoir d'erreur. 
@Jef-73, as-tu essayé avec une correction ou bien l'ajout de ta valeur ? 
Si c'est un ajout tu peux faire une pr sur la branche debug afin qu'on l'ajoute. J'incluerai les modifications sinon.

**Comment by Jef-73** [comment]
J'ai remplacé dans les trois fichiers du plugin le nom "SINST1" (chiffre) par "SINSTI" (lettre) et tout a fonctionné directement.
Ca a aussi résolu un problème de temps d'attente important (3 à 4 secondes) à chaque fois que j'ouvrais la page des paramètres de l'équipement ou que je voulais l'enregistrer. Maintenant c'est quasi instantané, comme pour tout autre équipement Jeedom.

Pour les spécifications Enedis, je n'ai trouvé nulle part de mention à SINST1 (chiffre) comme je disais. Voici le notice officielle de téléinformation client pour les compteurs Linky : https://www.enedis.fr/sites/default/files/Enedis-NOI-CPT_54E.pdf

J'ai pas trop compris "faire une pr" et tout ça :)
Suis pas très versé dans l'art du Github, désolé LOL

**Comment by ticed35** [comment]
Hum je sais pas ou j'avais vu ça alors.
Pas de troubles, je vais m'occuper des changements.

**Comment by ticed35** [comment]
@Jef-73, c'est poussé en beta https://github.com/NextDom/plugin-teleinfo/commit/ccaead127429a30926fed4be0d59f472825a5b47
Peux-tu valider ?

**Comment by Jef-73** [comment]
Je n'arrive pas à l'installer. J'imagine donc qu'il faut que je désinstalle le plugin stable et que j'installe le beta ?
J'ai peur de perdre mes données de production :-(

**Comment by ticed35** [comment]
Ne désinstalle pas tu vas perdre l'objet en effet. 
Vu la modification, attend demain que ça passe en stable pour tester.

**Comment by Jef-73** [comment]
Bon, j'ai installé le plugin en version beta par-dessus le stable et ça me reproduit le problème de blocages, donc je perds la production :(
Je tente de réinstaller le stable et remodifier manuellement les fichiers ...

**Comment by Jef-73** [comment]
PS : du coup j'ai vu l'erreur dans le log : 
[2019-10-28 15:11:14][ERROR] : Error on send request to jeedom, return code 500

**Comment by Jef-73** [comment]
J'ai remis la version stable, modifié manuellement les 3 fichiers pour mettre "SINSTI", relancé les dépendances : ça refonctionne correctement.

**Comment by ticed35** [comment]
Normal, la version va être poussé cette nuit ;)

**Comment by Jef-73** [comment]
J'ai tout sauvé, installé la version stable depuis Jeedom, relancé les dépendances : tout est OK maintenant, ça fonctionne parfaitement, y compris les libellés qui étaient absents (cause icône forcée).
Donc case à clore et merci pour ces corrections 👍
