### ISSUE TITLE
Problème Statistique

### ISSUE THREAD

**Issue by venk276** [NextDom/plugin-teleinfo#118]
## Description
Bonjour,
Lorsque je demande a afficher les statistiques de "BASE" et "PAPP" a partir du dashboard ou bien par "Analyse > Historique", le graph s'ouvre avec rien dedans puis 2secondes après j'ai une ligne en rouge qui s'affiche avec écris "500 : Internal Server Error"

Lorsque je vais dans le plugin Téléinfo puis le bouton "Maintenance"

Donnée | Nombre en base | A lisser | Plus ancienne valeur | Lissage
BASE | 2282297 | 2242962 | 2019-03-16 16:05:00 | Aucun | Bouton [Optimiser]
Puissance Apparente | 1371024 | 1337160 | 2019-03-16 16:05:00 | Moyenne | Bouton [ Optimiser (AVG) ]

Lorsque je clique sur les boutons il affiche "En cours..."
Et un bandeau jaune apparait "Optimisation de l'historique, cela peut prendre du temps. (La fenêtre peut être fermée)"
Mais lorsque je reviens plus tard sur le tableau rien n'a bougé.

Pouvez-vous m'aider? Merci

## Environnement
* **Version Jeedom 3.3.39
* **Platform box Jeedom Smart
* **Version du Plugin 4.6.5
* **Type de modem Cartelectronic Interface_USB_1_TIC:
* **Compteur linky non connecter au réseau:

## Logs
Ci-joint logs

En vous remerciant pour votre retour car je sèche.

[teleinfolog.txt](https://github.com/NextDom/plugin-teleinfo/files/4023783/teleinfolog.txt)
[teleinfo_deamon_conso.txt](https://github.com/NextDom/plugin-teleinfo/files/4023784/teleinfo_deamon_conso.txt)
[teleinfo_update.txt](https://github.com/NextDom/plugin-teleinfo/files/4023785/teleinfo_update.txt)

**Comment by ticed35** [comment]
Salut, 
C'est lié à l'issue #106  et un contournement est expliqué ici https://community.jeedom.com/t/maintenance-lisser-les-index-requete-sql/5776/7?u=ticed35
