### ISSUE TITLE
puissance active ?

### ISSUE THREAD

**Issue by diliact** [NextDom/plugin-teleinfo#119]
## Description
Bonjour, actuellement le compteur Linky envoie les index heures creuses et heures pleines, la puissance apparente mais pas la puissance active.

La puissance apparente permet de voir s'il faut changer la puissance du contrat (6 kVA, 9 kVA, etc.).
La puissance active permet de connaître le coût de la consommation d'électricité (W et donc Wh).

Il y a une petite différence entre les deux due à nos appareils contenant des composants réactifs (capacitifs ou inductifs), par exemple les transformateurs.

J'aimerais beaucoup connaître la puissance active.

Le module Qinergy (rien à voir avec Jeedom) se base sur la petite lumière qui clignote à chaque Wh consommé, donc la puissance active. Et cela offre un bon niveau de précision ! De l'ordre du Watt.

Serait-il possible d'afficher la puissance active en se basant sur la variation des index ? Cela serait assez simple à mettre en place : à chaque fois que l'index est incrémenté, la puissance active moyenne est recalculée. 1 Wh toutes les 10 secondes : 360 W ! Je ne connais pas la fréquence d'envoi de valeur des index mais c'est assez rapide, au moins toutes les deux secondes il me semble.

## Environnement
* **Version Jeedom**: 3.0
* **Platform**:
* **Version du Plugin (ex: 4.2.0)**: 4.6.5
* **Type de modem**: FTDI FT230X_Basic_UART
* **Compteur linky**: oui
* **Compteur standard ou historique**: historique

**Comment by ticed35** [comment]
Bonjour,
C'est déjà le cas avec la statistique conso moyenne dernière minute.
