### ISSUE TITLE
teleinfo.py: error: argument --port: expected one argument

### ISSUE THREAD

**Issue by phil7756** [NextDom/plugin-teleinfo#120]
## Description
Modem is not reachable
Always the same ...
usage: teleinfo.py [-h] [--apikey APIKEY] [--loglevel LOGLEVEL]
[--callback CALLBACK] [--socketport SOCKETPORT]
[--sockethost SOCKETHOST] [--cycle CYCLE] [--port PORT]
[--vitesse VITESSE] [--type TYPE] [--mode MODE]
[--cyclesommeil CYCLESOMMEIL] [--pidfile PIDFILE]
teleinfo.py: error: argument --port: expected one argument
usage: teleinfo.py [-h] [--apikey APIKEY] [--loglevel LOGLEVEL]
[--callback CALLBACK] [--socketport SOCKETPORT]
[--sockethost SOCKETHOST] [--cycle CYCLE] [--port PORT]
[--vitesse VITESSE] [--type TYPE] [--mode MODE]
[--cyclesommeil CYCLESOMMEIL] [--pidfile PIDFILE]
teleinfo.py: error: argument --port: expected one argument
usage: teleinfo.py [-h] [--apikey APIKEY] [--loglevel LOGLEVEL]
[--callback CALLBACK] [--socketport SOCKETPORT]
[--sockethost SOCKETHOST] [--cycle CYCLE] [--port PORT]
[--vitesse VITESSE] [--type TYPE] [--mode MODE]
[--cyclesommeil CYCLESOMMEIL] [--pidfile PIDFILE]
teleinfo.py: error: argument --port: expected one argument

## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**: 4.0.40
* **Platform**:Raspberry PI3B
* **Version du Plugin (ex: 4.2.0)**:2019.10.30
* **Type de modem**:
* **Compteur linky**:
* **Compteur standard ou historique**:

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by ticed35** [comment]
teleinfo.py: error: argument --port: expected one argument
==> Le port est mal renseigné sur le plugin.

**Comment by phil7756** [comment]
oui, merci j'avais bien compris mais comment faire ? ... comment le connaitre ? merci

**Comment by ticed35** [comment]
Dans la doc, partie installation. Il faut choisir le port du modem :
https://nextdom.github.io/plugin-teleinfo/fr_FR/#tocAnchor-1-8
La capture de la doc est un peu ancienne mais le principe reste valide : 
![image](https://user-images.githubusercontent.com/13416516/75176595-743e1c00-5702-11ea-9067-684b8550e948.png)
