### ISSUE TITLE
Anomalie sur Ma consommation du desktop

### ISSUE THREAD

**Issue by berniland** [NextDom/plugin-teleinfo#121]
Bonsoir Cedric
## Description
J'ai un décalage entre ma conso et l'évolution mensuelle :
![image](https://user-images.githubusercontent.com/48030185/74985670-3dcd7c00-5438-11ea-86f4-5e1c0c2061ba.png)

le mois en cours et le mois n-1 indiquent 190 et 24 alors que sur l'évolution nous sommes à 377 et 199 :+1: 
![image](https://user-images.githubusercontent.com/48030185/74985615-19719f80-5438-11ea-80f3-9de04b90a9ee.png)

Côté journalier c'est bon c'est identique.
J'ai un autre soucis ou plutôt une question : 
J'ai eu un soucis en mai dernier, ma conso HC indique anormalement 2464KWh ( pas possible et la facture est normal):
![image](https://user-images.githubusercontent.com/48030185/74985962-e11e9100-5438-11ea-8ff1-79ce7515d2a2.png)
Evidemment ma conso annuelle N-1 est fausse ( 5343 au lieu de ~ 2800)
je voulais savoir s'il était possible de "reduire" a la normal pour ne pas fausser les stat ?
une valeur qlq part a modifier ?
 par avance merci
## Environnement
* **Version Jeedom**: 3.3.39
* **Platform**: raspberry
* **Version du Plugin (ex: 4.2.0)**:4.6.5
* **Type de modem**: cartelectronic
* **Compteur linky**: oui
* **Compteur standard ou historique**: standard

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by berniland** [comment]
any update ? besoin de log ?

**Comment by ticed35** [comment]
Salut, 
Pour le problème mensuel tu peux essayer dans la zone maintenance de regénérer les stats mensuelles pour l'objet et voir si ça change. 
Concernant la valeur erronée c'est surement une mauvaise lecture à un moment. Il faut aller voir sur l'historique de l'index si il n'y a pas une valeur complètement différente.

**Comment by berniland** [comment]
Bonjour Cedric,
c'est mieux effectivement pour le mensuel après la regénération des stats.
pour ma valeur erronée, je ne trouve pas comment aller consulter l'historique des index ? peux tu me guider, il doit s'agir de la command STAT_YESTERDAY_HC, et après ... je trouve pas.
merci

**Comment by ticed35** [comment]
Désolé du retard. 
Pour corriger un historique il suffit d'aller sur Analyse / Historique puis de sélectionner la commande. 
Choisir l'intervale ou l'erreur est supposée être et simplement cliquer sur le point en erreur et valider sans mettre de valeur. Cela a pour effet de supprimer la valeur erronée.

**Comment by berniland** [comment]
Merci Cedric,
tout simplement :)
bonne soirée


   Berni
