### ISSUE TITLE
Création automatique via API

### ISSUE THREAD

**Issue by Seb-Othis** [NextDom/plugin-teleinfo#128]
## Description
Erreur dans le champs ADCO de l'objet lors de la création automatique d'un équipement via l'API
Le champs ADCO est toujours identique au nom du device alors que les informations sont bien différentes

## Etapes à reproduire (pour les bugs)
1. Appel de l'API avec l'argument suivant : $data = '{"device":{"Compteur":{"device":"Compteur","ADCO":"012345678901","PAPP":"00222","PTEC":"HP.."}}}';
2.
3.
4.

## Environnement
* **Version Jeedom**: 4.0.45
* **Platform**: Raspberry PI 2
* **Version du Plugin (ex: 4.2.0)**: 4.6.5
* **Type de modem**: RAS
* **Compteur linky**: RAS
* **Compteur standard ou historique**: RAS

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

![image](https://user-images.githubusercontent.com/59887067/77234174-ad0bcc80-6bac-11ea-9920-a6808c042141.png)

**Comment by ticed35** [comment]
Salut, 
C'est parce que le device doit être l'ADCO ou l'ADSC suivant le compteur. 
Cf doc du plugin https://nextdom.github.io/plugin-teleinfo/fr_FR/#tocAnchor-1-14
