### ISSUE TITLE
Remontée partielle de données Edf

### ISSUE THREAD

**Issue by bleuet11** [NextDom/plugin-teleinfo#130]
## Description
Mon installation se compose d'un compteur linki (en mode historique) auquel est connecté un wemos mini D1 qui transmet en wifi les données vers jeedom installé sur un Py. 
toutes les données du compteur sont correctement lues (parfois en double) et arrivent sur jeedom .
au moment de l'interprétation et de l'envoi vers le plugin de mise en forme téléinfo (par message post) certaines données ne sont pas envoyées sans que je n'ai d'explication évidente, d'autant que parfois, toutes les données sont bien transmises (cf log jeedouino.3.xlsx).
le plugin teleinfo lui même interprète correctement toutes les données reçues par post (cf log teleinfo)

## Etapes à reproduire (pour les bugs)
1. 
2.
3.
4.

## Environnement
* **Version Jeedom**: 3.3.39
* **Platform**: raspery py 3B+
* **Version du Plugin (ex: 4.2.0)**: 2020-02-18 02:21:23
* **Type de modem**: wemos mini D1
* **Compteur linky**: particulier - consommateur
* **Compteur standard ou historique**: mode historique

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.
Extrait du log du module weemos dans un Excel
log du module téléinfo
[jeedouino(3).xlsx](https://github.com/NextDom/plugin-teleinfo/files/4666724/jeedouino.3.xlsx)
[teleinfo.txt](https://github.com/NextDom/plugin-teleinfo/files/4666725/teleinfo.txt)

**Comment by ticed35** [comment]
Salut, 
Il s'agit plus du côté du jeedouino, je ne supporte cependant pas ce montage. 
Je t'invite à poser ta question sur https://community.jeedom.com/ avec le tag plugin-jeedouino
