### ISSUE TITLE
Utilisation d’un second compteur pour de la production électrique

### ISSUE THREAD

**Issue by moumout31** [NextDom/plugin-teleinfo#134]
## Description
Bonjour,
Je possède un modem Cartelectronic 2 compteurs (un pour la conso et un pour la production), et je ne trouve pas comment configurer le 2nd compteur en mode production comme indiqué dans la documentation (Utilisation d’un second compteur pour de la production électrique).
Merci
![Capture](https://user-images.githubusercontent.com/67594877/86022808-22e4c700-ba2b-11ea-93c7-1bb3a6523717.PNG)

## Environnement
* **Version Jeedom**: v4.0.58
* **Platform**: Raspberry Pi 3B+
* **Version du Plugin (ex: 4.2.0)**: 28/06/2020
* **Type de modem**: Cartelectronic 2 compteurs
* **Compteur linky**: Pour la consommation en mode historique
* **Compteur standard ou historique**: Pour la production PV

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by ticed35** [comment]
Salut, 
Pas besoin de configurer de 2ème modem vu que c'est le cartelectronic qui s'occupe de remonter les informations des 2 compteurs.
Cependant il faut noter que le mode production est associé au type linky en général, et donc le mode "standard" de edf. 
Le modem2compteurs n'est capable d'utiliser qu'un mode à la fois. Donc il faut que les 2 compteurs soient du type linky en mode standard.

**Comment by moumout31** [comment]
Merci pour ta réponse.
