### ISSUE TITLE
probleme avec le plugin teleinfo

### ISSUE THREAD

**Issue by titof2375** [NextDom/plugin-teleinfo#139]
## Description
plus re remonte de mon compteur
## Etapes à reproduire (pour les bugs)
1.je ne sais pas 
2.
3.
4.

## Environnement
* **Version Jeedom**:4.061
* **Platform**:rpi
* **Version du Plugin (ex: 4.2.0)**:4.65
* **Type de modem**:modem teleinfo
* **Compteur linky**:linky

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by c4software** [comment]
Idem ça semble ici. Plus rien depuis 2 jours, aucun changement hardware de mon côté.

**Comment by noyax** [comment]
je viens de m'appercevoir du plantage qui a eu lieue depuis qq jours comme vous. J'ai débranché l'usb du téléinfo, rebranché puis relancé jeedom et ça fonctionne depuis.
