### ISSUE TITLE
Fonctionnement sur debian Bullseye

### ISSUE THREAD

**Issue by JeanBaptiste-elec** [NextDom/plugin-teleinfo#146]
## Etapes à reproduire (pour les bugs)
1. Mettre à jour debian ou installer la dernière version stable (11 Bullseye)

## Contexte
Lors de la mise à jour de debian sur la dernière version stable, le plugin ne fonctionne pas (problème probable de compatibilité de version Python).

## Environnement
* **Version Jeedom**: 4.1.25
* **Platform**: Debian 11 bullseye
* **Version du Plugin (ex: 4.2.0)**: 4.6.5
* **Type de modem**: Cartelectronic 1 modem
* **Compteur linky**: oui
* **Compteur standard ou historique**: historique

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

**Comment by JulienArcades78** [comment]
Bonjour, 
Effectivement… mais même en forçant python 2.7 une (autre) erreur survient 

Effectivement en Python 3 on se fait jeter parce qu'il manque des parenthèses ligne 61. 

`user@computer:~ $ sudo python3 /var/www/html/plugins/teleinfo/ressources/teleinfo.py 
  File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 61
    print "Terminating..."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Terminating...")?`

Mais en revenant en Python 2.7 il y a autre chose, mais je comprends moins : 
`user@computer:~ $ sudo python2 /var/www/html/plugins/teleinfo/ressources/teleinfo.py 
Error: importing module from jeedom folder
No module named requests`

Les erreurs listées ci-dessous sont visibles également dans les logs Jeedom.

**Comment by Darkensen** [comment]
Bonjour,

j'ai le même problème malgré l'installation de python2, puis de pip2, et de requests via pip2 :'( une idée ?
La réintallation des dépendances n'a rien changé

**Comment by JeanBaptiste-elec** [comment]
Bonjour,

J'ai depuis réussi à faire fonctionner le fichier sous python 3. N'étant absolument pas développeur, je pense que mon travail est assez sale, mais ça fonctionne.
Je suis actuellement en vacances, je peux vous transmettre le fichier modifié pour essai sur vos machines (avec vos retours éventuel).

**Comment by Gis70** [comment]
Salut, toujours d'actu ou solutionner par la develop 4.7 ?

**Comment by JeanBaptiste-elec** [comment]
De ce que j'ai lu, oui, toujours d'actualité sur la version develop.

**Comment by Darkensen** [comment]
Je pense pas que ce soit lié à la version de Jeedom mais plutot au fait que sur Bullseye il n'y a plus de Python2.
Donc il faudrait que NextDom redev son plugin pour le passer en Python3

**Comment by JeanBaptiste-elec** [comment]
Oui, c'est bien cela. Bullseye ne supporte que très partiellement python 2.7, donc ça ne peut pas fonctionner.
Je pense bientôt proposer une version compatible avec bullseye et la traduction des registres et relais virtuels.

**Comment by superMoYoX** [comment]
> Oui, c'est bien cela. Bullseye ne supporte que très partiellement python 2.7, donc ça ne peut pas fonctionner. Je pense bientôt proposer une version compatible avec bullseye et la traduction des registres et relais virtuels.

Salut Jean-Baptiste !

J'ai installé Python 2.7, l'erreur du log du daemon est différente, en effet, que sans la 2.7 mais je n'y comprends rien.
Tu saurais m'aiguiller sur le "quoi du où" modifier ou c'est vraiment trop chiant ?

**Comment by Darkensen** [comment]
C'est pas si simple de passer de Python 2 a 3 :(
C'est pas hyper compliqué, mais si le mainteneur du projet ne répond plus ça va être compliqué il me semble (je suis pas dev juste 'scripteur' en Python..)
Quelqu'un a une idée ? Pour reprendre le lead sur ce projet et pouvoir publier des updates ?

**Comment by JeanBaptiste-elec** [comment]
Noyax37 semble être assez bien parti pour proposer la mise à jour, GiDom a l'accès aux droits du plugin.

**Comment by superMoYoX** [comment]
Ok merci pour les infos les gens.
J'ai update un jeedom "esclave" vers bullseye, le seul plugin qu'il utilise en plus de jeelink c'est celui-ci ^^'
L'air con.
J'étais même prêt à fouiller dans le script alors que je ne code pas en python.

**Comment by vince122** [comment]
Bonjour à tous,

J'ai le même problème que vous, est-ce que quelqu'un à reussi a faire fonctionner le plugin avec Debian Bulseye ?

**Comment by JeanBaptiste-elec** [comment]
Normalement, le plugin en version develop fonctionne (beta sur le jeedom market).
Pourriez-vous confirmer ?

**Comment by vince122** [comment]
> Normalement, le plugin en version develop fonctionne (beta sur le jeedom market). Pourriez-vous confirmer ?

En effet ça fonctionne en version Beta du plugin, merci beaucoup !

**Comment by JeanBaptiste-elec** [comment]
Problème solutionné par mise à jour en version developp.

**Comment by JeanBaptiste-elec** [comment]
Oui, testé sur debian 11 et fonctionnel.

**Comment by Darkensen** [comment]
Bon bah yapuka :)
Merci ! C'était le seul point bloquant pour repasser sur debian 11 , je me sentais a la traîne !
