### ISSUE TITLE
Info Production sur Panel Teleinfo

### ISSUE THREAD

**Issue by tomtom7810** [NextDom/plugin-teleinfo#148]
Bonjour,

J'ai actuellement un seul compteur Linky qui permet de mesurer la consommation et la production (je possède des panneaux solaires qui injectent le surplus dans le réseau).
La communication avec le compteur fonctionne bien et je récupère bien les index de consommation et de production.

Par contre, dans le panel teleinfo, j'ai que les informations de la consommation qui apparaissent.

Est-il possible d'avoir également les informations sur la production ?
Cela serait top de pouvoir voir l'évolution sur les mois passés.

Merci.

Cordialement,
Thomas

## Environnement
* **Version Jeedom**: 4.1.27
* **Platform**: Raspberry
* **Version du Plugin (ex: 4.2.0)**: 2021-02-04 01:01:47
* **Type de modem**:
* **Compteur linky**: Linky
* **Compteur standard ou historique**: Standard

**Comment by noyax** [comment]
Ok depuis qq versions
