### ISSUE TITLE
Probleme de version python

### ISSUE THREAD

**Issue by guy38370** [NextDom/plugin-teleinfo#157]
## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Contexte:
Le daemon ne demarre pas et il y a des erreurs dans les logs qui font penser à un problème de version python
Python 2.7 est installé car lorsque je veut l'installer apt m'indique qu'il l'ai déjà

Quelles sont les manipulatons à faire pour valider la bonne version python pour le plgin teleinfo , sans risquer de planter jeedom ou les autres plugins installés ?

uname -a
Linux jeedomrpi4 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

python --version    Python 3.9.2
python3 --version  Python 3.9.2
pip --version          pip 22.0.4 from /home/pi/.local/lib/python3.9/site-packages/pip (python 3.9)
pip3 --version        pip 22.0.4 from /home/pi/.local/lib/python3.9/site-packages/pip (python 3.9)

sudo apt install python2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python2 is already the newest version (2.7.18-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

teleinfo_daemon_conso
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Terminating...")?
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 61
print "Terminating..."

voir fichiers diag joints

## Environnement
* **Version Jeedom**:4.2.14
* **Platform**:Raspberry PI 4
* **Version du Plugin (ex: 4.2.0)**:2022-04-16 01:02:09
* **Type de modem**:module USBTIC 1 compteur V2
* **Compteur linky**:compteur de productio linky avec TIC en mode standard
* **Compteur standard ou historique**:

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.
[teleinfo_diag.txt](https://github.com/NextDom/plugin-teleinfo/files/8556408/teleinfo_diag.txt)
[teleinfo_export.txt](https://github.com/NextDom/plugin-teleinfo/files/8556410/teleinfo_export.txt)
[info.json.txt](https://github.com/NextDom/plugin-teleinfo/files/8556412/info.json.txt)

**Comment by noyax** [comment]
Normalement la version stable tourne sous python 2.7 et la version beta sous python 3.

**Comment by guy38370** [comment]
merci noyax mais seule la version stable est accessible sur le market
A noter que le changelog n'est pas à jour

un lien pour charger la version python 3 ?
Ou un autre workaround ?

**Comment by Gis70** [comment]
Salut, sous le market jeedom il y a la version Beta.

![image](https://user-images.githubusercontent.com/16589132/165360297-0688a937-4519-4283-93ab-e8480e6a5a20.png)

**Comment by guy38370** [comment]
merci Gis70 

En fait je ne voyait pas la version beta car je ne les avait pas activées dans mon profil sur le market

Je confirme que la version beta fonctionne sur ma box . (python 3.9.2)

Probleme décrit en tete resolu

**Comment by Gis70** [comment]
J'en suis ravie. A+
