### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by SqualCox** [NextDom/plugin-teleinfo#160]
## Description
La création du compteur et les commandes sont faite.
Mais lorsque je veux enregistré le compteur sans avoir faire de modification le plugin me donne une erreur 500 internal server error
Il est donc pas possile de faire de modification sur le compteur
Exple : ajouter une information comme la consommation du J-1

## Etapes à reproduire (pour les bugs)
1. ouvrir le compteur créé
2. Faire une sauvegarde
3.
4.

## Environnement
* **Version Jeedom**: 4.3.10
* **Platform**: Debian 10
* **Version du Plugin (ex: 4.2.0)**: 4.6.5
* **Type de modem**: Modem Téléinformation EDF - 1 compteur [https://www.amazon.fr/gp/product/B01DLBVN3M/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1](url)
* **Compteur linky**: oui
* **Compteur standard ou historique**: historique

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

0000|[Mon Nov 21 19:36:24.692832 2022] [php7:error] [pid 23596] [client xxx.yyy.zzz.xyz:48972] PHP Fatal error:  Uncaught Error: Call to undefined method teleinfoCmd::setEventOnly() in /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php:1023
0001|Stack trace:
0002|#0 /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php(991): teleinfo->createOtherCmd()
0003|#1 /var/www/html/core/class/DB.class.php(232): teleinfo->postSave()
0004|#2 /var/www/html/core/class/eqLogic.class.php(1022): DB::save(Object(teleinfo), false)
0005|#3 /var/www/html/core/ajax/eqLogic.ajax.php(498): eqLogic->save()
0006|#4 {main}
0007|thrown in /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php on line 1023, referer: http://x.y.z/index.php?v=d&m=teleinfo&p=teleinfo&id=496

**Comment by noyax** [comment]
Bonjour, soit tu passes à la version béta, ce que je te conseille fortement, soit tu modifies le fichier html/plugins/teleinfo/core/class/teleinfo.class.php en virant les 2 lignes qui contiennent setEventOnly

**Comment by SqualCox** [comment]
Ok, merci pour le retour.
A moi de voir, si je passe en Beta ou modifier les fichiers.
je vais prendre l'option de modifier les fichiers et si trop de prblème, je passerais en bêta
