### ISSUE TITLE
Probleme du plugin avec option Tempo EDF - erreur 500

### ISSUE THREAD

**Issue by Yourry** [NextDom/plugin-teleinfo#165]
## Description
Bonjour,
J'utilise depuis quelques temps sans trop de soucis ce plugin sur ma box Jeedom avec un config simple: mode historique, d'abord sur un vieux compteur puis ensuite sur un linky (migration oblige) et un abonnement EDF classique de base sans heure creuses ni pleines.
Mais je suis passé au 01/01/2023 a un abonnement tempo et la cata, le pluggin déconne. 
J'ai tenté simplement une désinstallation puis ré-installe (en perdant l'historique au passage :( ) mais rien n'y fait, le pluggin ne fonctionne pas correctement.
Il lit bien les trames et semble en décoder quelqu'unes quand même :

![image](https://user-images.githubusercontent.com/5098104/210861752-5ced10ea-dde3-4ea5-8d69-35b62b2d79da.png)

Mais cela bug pas mal, impossible d'étider la tuile ou même une simple sauvegarde :

![image](https://user-images.githubusercontent.com/5098104/210862021-fdaf6d6f-b379-4e32-bce7-469766a907cb.png)

Ou même plus de conso journalière.

## Environnement
* **Version Jeedom**:  4.3.12
* **Platform**: VM sur proxmox
* **Version du Plugin (ex: 4.2.0)**: 2022-04-16 01:02:09
* **Type de modem**: rs232
* **Compteur linky**: oui
* **Compteur standard ou historique**: historique

## Logs
Voici les logs en mode débug, j'ai juste changé le numéro du compteur. 

[teleinfo_deamon_conso.txt](https://github.com/NextDom/plugin-teleinfo/files/10355070/teleinfo_deamon_conso.txt)
[teleinfo_update.txt](https://github.com/NextDom/plugin-teleinfo/files/10355071/teleinfo_update.txt)
[teleinfo.txt](https://github.com/NextDom/plugin-teleinfo/files/10355072/teleinfo.txt)

Merci par avance, si besoin de plus d'info ou autre n'hésitez pas.
Amicalement,

**Comment by noyax** [comment]
bonsoir @Yourry , l'erreur 500 est due a une évolution de jeedom et comme le plugin n'est plus maintenu en version stable ça pose pb. Alors soit tu modifies à la main le fichier qui pose pb soit tu passes en version béta

**Comment by Yourry** [comment]
Salut,
@noyax au top pour ton retour, j'ai bien supprimé les deux commandes "setEventOnly" de la ligne de code et effectivement je n'ai plus cette erreur 500.
Et effectivement le plugin semble de nouveau fonctionner.
Merci pour ton retour !
