### ISSUE TITLE
Call to a member function getId() on null

### ISSUE THREAD

**Issue by llaumgui** [NextDom/plugin-teleinfo#26]
## Description
Dans mon panel, en cliquant sur "vérifier", j'ai une erreur 500:
```
[Wed Mar 14 18:35:33.995963 2018] [proxy_fcgi:error] [pid 10293:tid 548329746848] [client 192.168.1.1:46072] AH01071: Got error 'PHP message: PHP Fatal error:  Call to a member function getId() on null in /var/www/html/plugins/teleinfo/core/ajax/teleinfo.ajax.php on line 108
', referer: https://plop.plop.plop/index.php?v=d&m=teleinfo&p=panel
```
## Etapes à reproduire (pour les bugs)
1. Aller sur le panel.
2. Cliquer sur vérifier.

## Contexte:
* Nouveau compteur.
* Tache planifiée lancée pour ne pas attendre 24H.
* Core Teleinfo : 2.6.4

## Proposition de solution (optionnel):
Je regarde.

## Environnement:
* **Version Jeedom**: 3.1.7
* **Platform**: ODroid
* **Version du Plugin**: 2018-03-14 16:35:15

**Comment by ticed35** [comment]
Salut, 
Je sais d'ou provient le bug.
Je pousse un hotfix dès que j'ai la solution.

**Comment by llaumgui** [comment]
J'ai vu passer une MAJ aujourd'hui, on est d'accord que le hotfix n'est pas dedans ?

**Comment by ticed35** [comment]
En effet, tu aurais vu le commit passer ici ;)

**Comment by ticed35** [comment]
Normalement cette partie est bonne avec le commit cb71666.
Reste à voir ton souci de perd du panel sur l'autre issue.
