### ISSUE TITLE
Pannel plus gourmand

### ISSUE THREAD

**Issue by llaumgui** [NextDom/plugin-teleinfo#32]
## Description
Dans mon panel, j'ai une erreur 500:
```
[Thu Mar 22 11:17:31.250998 2018] [proxy_fcgi:error] [pid 13006:tid 547893539232] [client 192.168.1.1:35524] AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/core/ajax/cmd.ajax.php on line 280
```
J'ai l'impression que le panel est plus gourmand...

## Etapes à reproduire (pour les bugs)
1. Aller sur le panel.

## Contexte:
* Core Teleinfo : 2.6.4

## Proposition de solution (optionnel):
Je regarde.

## Environnement:
* **Version Jeedom**: 3.1.7
* **Platform**: ODroid
* **Version du Plugin**: 2018-03-21 03:10:12

**Comment by ticed35** [comment]
Salut, 
L'erreur 500 est elle toujours présente ?

**Comment by llaumgui** [comment]
Yes :(

**Comment by llaumgui** [comment]
Pareil avec la version de ce jour.

**Comment by llaumgui** [comment]
Nonpareil en 2.7.2 mais je me demande si j'ai bien tous les stats et que le problème ne viens pas de là:
![screenshot-2018-4-21 teleinfo - jeedom](https://user-images.githubusercontent.com/411360/39087243-902a6b84-459e-11e8-9dab-8f0e9660c563.png)
Du coup avec des stats en mois ça while peut-etre ?

**Comment by llaumgui** [comment]
Paril avec la maj de ce jour... Mais : j'ai des NOK sur:
* Conso totale Aujourd'hui
* Conso Mois en cours
* Conso Année en cours

Alors que j'ai (re)sauvé mon objet...

**Comment by llaumgui** [comment]
Bonjour,

j'ai profité de mes vacances pour [mettre à jour ma box de Debian 8 vers Debian 9](https://blog.kulakowski.fr/post/jeedom-installation-update-sous-odroid) et donc de PHP 5.6 vers 7.

Du coup:

- plus d'erreur 500 depuis.
 - Mais, toujours des stats quotidienne à 0 et des NOK
![screenshot_2018-08-20 panel - jeedom](https://user-images.githubusercontent.com/411360/44352353-6d4aa380-a4a4-11e8-9963-2d24ad61c023.png)

Du coup, on ferme ce ticket et on en ouvre un autre pour suivre les problème de NOK ?

**Comment by ColonelMoutarde** [comment]
Oui, c’est mieux stp.
