### ISSUE TITLE
/bin/sh: 1: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by ticed35** [NextDom/plugin-teleinfo#42]
## Description
Problème d'encodage de certaines trames provoquant un affichage d'erreur. 

## Etapes à reproduire (pour les bugs)
1. Lancer le démon et attendre

## Environnement
* **Version Jeedom**: Toutes
* **Platform**: Toutes
* **Version du Plugin (ex: 2.6.0)**: 3.0.0
* **Type de modem**: Tous impactés
* **Compteur linky**: 
- [x] Oui 
- [x] Non

**Comment by jolypas** [comment]
je veux bien aider car j'ai le problème.
Que puis je faire ?

**Comment by ticed35** [comment]
Salut, 
Merci de la proposition, j'ai surtout besoin de gens qui pourrait regarder le code et apporter un oeil extérieur la dessus :)

**Comment by benlbrm** [comment]
J'ai aussi le pb. Est-ce que chez vous il empêche toute remontée d'info depuis le modem ?
Mon installation fonctionnait et depuis avril on va dire que je ne reçoit plus rien dans les trames.

**Comment by clem1233** [comment]
Je l'ai également après branchement d'un second modem pour récupérer les infos du compteur de production d’électricité. Le premier fonctionne toujours, mais impossible d'avoir une trame de données pour le second. Peux-tu rajouter des traces pour qu'on t'aide à débugger ?

**Comment by olfax** [comment]
J'avais le même problème (sur un raspberry pi 1).
J'ai passé pas mal de temps à debugger, mais j'ai fini par le résoudre. 

J'ai ajouté un time.sleep(2) juste après le thread.start()

Pour mon cas, cela provenait du fait que lorsque le thread se lancait et voulait executait self.cmd + send_data, le send_data était mis à zero par le thread principal qui lit les données
