### ISSUE TITLE
Données santé pour linky

### ISSUE THREAD

**Issue by ticed35** [NextDom/plugin-teleinfo#43]
## Description
Ajouter la gestion des données santé pour les compteurs linky

**Comment by berniland** [comment]
Voici les screenshots dans l'ordre :
Les 2 sur la santé:
![sante1](https://user-images.githubusercontent.com/48030185/53828170-3c801680-3f7d-11e9-8b0e-062e2bbc7e00.png)
![sante2](https://user-images.githubusercontent.com/48030185/53828184-430e8e00-3f7d-11e9-9d8e-e73f0b063e12.png)
L'objet dans le dashboard:
![dashb1](https://user-images.githubusercontent.com/48030185/53828191-486bd880-3f7d-11e9-9de0-0e2ade5b85f0.png)
Puis le graph :
![graph1](https://user-images.githubusercontent.com/48030185/53828336-a8fb1580-3f7d-11e9-9122-ef80336a0f26.png)

**Comment by ticed35** [comment]
@berniland, tu es producteur d'électricité également ?

**Comment by berniland** [comment]
bonjour cedric,
non pas producteur,
j'ai vu un update de teleinfo sur mon jeedom hier soir, je suppose que
c'est toi qui la mis sur le github ?

merci et bonne journée


   Berni

**Comment by ticed35** [comment]
Oui j'ai poussé quelques maj. 
Maintenant tu devrais avoir les stats qui se calculent aussi sur la dernière beta.

**Comment by ticed35** [comment]
Données prisent en compte.

**Comment by berniland** [comment]
Bonsoir Cedric,
J'ai commencé à regarder les données enregistrées. 
je pense avoir un petit soucis sur le dashboard " ma consommation" si je le compare avec 
"evolution journalière" & "évolution mensuelle":
- évolution journalière: c'est bon 
-évolution mensuelle : c'est pas bon  
dans le use case, j'ai le mois a 109,421KWh ( je suppose le mois en cours)
et le Mois N-1 à 24,143KWh
![image](https://user-images.githubusercontent.com/48030185/74284090-598f9e80-4d23-11ea-94c1-4171c20c02b2.png)

Si je compare avec l'évolution mensuelle je devrais être en N-1 (janvier) à 377,824KWh :

![image](https://user-images.githubusercontent.com/48030185/74284885-f69f0700-4d24-11ea-9b7e-7a448831f2fc.png)



Il y a aussi un petit décalage avec le mois en cours mais peut être que le calcul ne se fait pas en même temps ( j'ai pour tester cliqué sur verifier l'intégrité des données):
donc : le mois en cours affiche 109,421 KWh alors que sur evol mensuelle(fevrier) 118,941KWh .

Par avance merci

**Comment by berniland** [comment]
j'ai une autre question ( j'en profite)
c'est pas bien grave mais ça fausse mes stats pour 2019 
il y a eu un bug au mois de mai ou je me retrouve avec 2464 KWh en heure creuse au lieu en moyenne 120 KWh ( pas de pic en Euros sur ma facture, ouf !)
![image](https://user-images.githubusercontent.com/48030185/74285730-ad4fb700-4d26-11ea-953f-b3c8e650c328.png)
y a t il un moyen de retrouver cette valeur dans les données et la modifier ?
