### ISSUE TITLE
Problème avec IRMS1 et SINSTI 

### ISSUE THREAD

**Issue by micromad** [NextDom/plugin-teleinfo#49]
## Description
Depuis la dernière mise à jour, version 3.1.0, les champs SINSTI et IRMS1 ne sont plus remontés dans Jeedom alors qu'ils apparaissent dans les trames ErDF de production électrique.

curl -L -s -G --max-time 8 http://192.168.1.72:80/plugins/teleinfo/core/php/jeeTeleinfo.php -d 'api=<clé_api>&SINSTI=00927&URMS1=237&ADCO=xxxxxxxxxx'

Je tiens à signaler que le compteur avait été créé avec la branche develop version 3.1.1.
De plus dans les logs, chaque trame génère le message :
[2018-05-16 16:06:33][INFO] : Création de la commande SINSTI sur l'ADCO xxxxxxxxxxxx

De plus le plugin avait change par défaut la définition de ces deux champs et ceux-ci pointaient sur le premier de la liste de choix dans la page "commandes", c'est-à-dire sur ARDS1.

## Environnement
* **Version Jeedom**:
* **Platform**:
* **Version du Plugin (ex: 2.6.0)**: 3.1
* **Type de modem**: Cartelectronic
* **Compteur linky**: 
- [x] Oui 
- [ ] Non

* **Mode du compteur**: Standard

**Comment by micromad** [comment]
Bon je suis repassé en version stable et j'ai sauvegarder à nouveau ma config et maintenant j'ai bien les remontés de IRMS1 et SINSTI.
Par contre maintenant quand je clique sur Sauvergarder, il ecrit "une commande (HEALTH) existe deja" et si je rappuis sur le bouton ça fonctionne. Hors il n'existe pas de commande HEALTH au sein du plugin.

T'as une idée @ticed35 ?

**Comment by ticed35** [comment]
Salut, 
Les valeurs sont bien présente dans les 2 branches. Ces valeurs doivent remonter peu importe si il s'agit de stable ou beta. 
La commande health existe, elle est interne au plugin.

**Comment by ticed35** [comment]
@micromad tout est bon ?

**Comment by micromad** [comment]
Ben je n'ai rien fait mais en meme temps ce probleme n'est pas reapparu.
On va dire ok.
