### ISSUE TITLE
Refaire fonctionner le mode 2 compteurs. 

### ISSUE THREAD

**Issue by ticed35** [NextDom/plugin-teleinfo#5]

**Comment by StepG38** [comment]
Hello
Désolé mais plus rien ne focntionne chez moi !!
Merci pour votre aide

**Comment by ticed35** [comment]
Bonjour, 
En cas de soucis sur le mode 2 compteurs est-il possible d'exécuter un diagnostique (Fonction depuis 3.0.0) et poster le fichier ici. 
Merci

**Comment by ticed35** [comment]
@StepG38 toujours des soucis sur le demon 2 compteurs ? Quels sont les logs actuels ?

**Comment by StepG38** [comment]
Bonjour Cédric,
Désolé pour le retard dans la réponse !
En fait je viens juste de terminer de poser mes panneaux photovoltaïques.

Le compteur de production est branché avec un module Wifinfo réalisé par
Rol-rider. Il semble fonctionner.
Sauf les stats qui reprennent les valeurs du 1er compteur (teleinfo USB
cartelectronic 1 compteur sur le général).

*Tu peux pas regarder pourquoi si 2 compteurs la conso du jour par exemple
est calculée toujours sur le même compteur ?*

Je viens de faire la mise à jour en 3.0.1.
J'ai vu que tu a ajouté le bouton Linky. Pour le moment je ne l'ai pas : a
voir quand Enedis me le changera !

Je vais tester en branchant mon deuxième module USB pour la production et
mettre le wifinfo sur ma PAC et ainsi avoir mes 3 compteurs.
Pour le moment je ne vais pas utiliser le module cartelectronic 2 compteurs
car j'en ai 2 simples et de la place USB.
Je te tiens au courant.
Merci encore pour ton aide !
A+
Stéphane


2018-05-09 5:48 GMT+02:00 Cédric <notifications@github.com>:

**Comment by StepG38** [comment]
Re,
Je viens de faire des tests aprés avoir éteint mon Wifinfo car avec les 3
ensembles les données se mélangé !!! ( je vérais par la suite pour le
compteur de la PAC)
1) Suppression complet du plug in + redémarrage
2) installation plugin en Beta 3.0.1
3) Branchement des 2 compteurs (Générale + PV) avec 2 modems USB
cartelectronic.
4 ) Paramétrage avec compteur production pour le PV






Résultat : Les données HP, HC, PAI, IP1, IP2 et IP3 sont OK !!
Par contre les stats conso jour, mois et année sont les mêmes pour les 2
compteurs !!


Merci par avance de ton aide !
Bien cordialement
Stéphane




2018-05-09 5:48 GMT+02:00 Cédric <notifications@github.com>:

**Comment by ticed35** [comment]
Hello, 
Oui la partie statistique ne gère pas bien les multi compteurs. 
Je vais avoir du travail la dessus ^^

**Comment by StepG38** [comment]
Ok
Merci pour ton retour
C'est compliqué les stats ?
A+
Stéphane

**Comment by StepG38** [comment]
Hello,
Après quelque jours de test, les 2 boitiers USB 1 compteur semble
fonctionner.
J'oubli les stats en multicompteur.
Par contre si je connecte mon Wifinfo, mon compteur PV reçois les index de
mon wifinfo par intermittence et le compteur du wifinfo n'apparait pas dans
le plugin !
Je vais oublier le wifinfo pour le moment.
Je souhaite arriver à avoir mais 3 compteurs.
Je vais essayer de nouveau avec mon boitier 2 compteurs en actionnant le
mode 2 compteurs + 1 module 1 compteur USB sur la production.
Tu pense que cela peux fonctionner ?
Merci pour ton aide
Stéphane

2018-05-09 15:17 GMT+02:00 Cédric <notifications@github.com>:

**Comment by StepG38** [comment]
Hello Cédric,
Je viens de tester avec 3 compteurs et ça fonctionne enfin !!!!!! YES
Un grand merci à toi pour ton aide et le temps que tu as passé !!
J'ai donc 1 boitier cartelectronic 2 compteurs avec ma PAC et la production
PV + 1 boitier cartelectronic sur le compteur général.
Bon les stats ne fonctionnent pas mais je calcul la conso de l'année sur
mon virtuel avec la valeur relevé le 1er janvier.
Grand, Grand merci à toi !!
A+
Stéphane

2018-05-09 15:17 GMT+02:00 Cédric <notifications@github.com>:
