### ISSUE TITLE
Besoin de comparaison du mode standard

### ISSUE THREAD

**Issue by micromad** [NextDom/plugin-teleinfo#51]
## Description
J'ai des problemes de signal de la TIC au niveau du Linky. Des evenements rares et indetermines font que le compteur de production (dans mon cas) oscille alors qu'il ne devrait que croitre. Comme ces evenements sont rares, il met difficile d'en determiner l'origine : probleme du Linky, du boitier cartelectronic, probleme du plugin, ... c'est pourquoi j'ai besoin de retour d'autre utilisateurs. 

Le plugin fonctionne parfaitement en mode historique sur mon autre Linky de consommation.

## Etapes à reproduire (pour les bugs)
1. Juste utiliser le plugin en mode standard avec un Linky

## Contexte
Utilisation du plugin teleinfo en mode standard.

## Environnement
* **Version Jeedom**: 3.2.7
* **Platform**: Rpi3 Raspian Jessie
* **Version du Plugin (ex: 2.6.0)**: 3.1.0
* **Type de modem**: Cartelectronic
* **Compteur linky**: 
- [x] Oui 
- [ ] Non

* **Mode du compteur**:

## Logs
![chart](https://user-images.githubusercontent.com/6885515/40392805-364084b8-5e1d-11e8-8fb2-8554bd81d9e2.png)

**Comment by micromad** [comment]
@ticed35 je suis en train de reecrire la partie "compute_checksum" pour le mode standard qui ne fonctionnait pas dans le fichier teleinfo.py.
Je la push des que je l'ai testee

**Comment by ticed35** [comment]
@micromad je valide que ce n'est pas géré actuellement.

**Comment by micromad** [comment]
Bon j'ai debugue et je suis en train de normaliser le code en PEP8, le rendre compatible python 3 et de changer la détection des frames pour qu'elle colle à la définition EDF.

Dès que j'ai testé cela, je te l'envoie.

**Comment by micromad** [comment]
@ticed35 j'ai implémenté hier une version debugge de teleinfo.py pour le mode standard.
Je la laisse tourner le temps de voir si tout est ok et je t'envoie les sources à moins que tu autorises la création de nouvelle branche que je pourrais pusher. Pour l'instant le signal est propre :).

Parrallèlement je développe un package Python de teleinfo indépendant de Jeedom et je fournirai le driver pour l'utiliser sous Jeedom. Je fais une refonte totale avec prise en compte de la teleinfo et des specs du document EDF, le tout en full objet et avec la compatibilité Python3 et la doc Sphinx.
