### ISSUE TITLE
Problème sur PLUGIN TELEINFO avec linky mode Historique

### ISSUE THREAD

**Issue by Laperche** [NextDom/plugin-teleinfo#53]
## Description
Pas d'information remontées par le plugin.
Pas de détection de mon compteur.
## Etapes à reproduire (pour les bugs)
Log des infos reçues sous windows avec le même module, donc la sortie TIC de mon compteur linky est bien active.
Dans le logiciel pour recevoir ces infos je précise mode historique à 1200 bds sinon je ne reçois rien.

OPTARIF BASE 0
ISOUSC 30 9
BASE 000063207 ]
PTEC TH.. $
IINST 003 Z
IMAX 060 E
PAPP 00790 1
HHPHC A ,
MOTDETAT 000000 B

ADCO 021860603752 <

## Contexte
Module CarteElectronique USB (Pas le model en RAIL DIN)
Vitesse 1200 bds
## Environnement
* **Version Jeedom**:Dernier Core
* **Platform**: Windows / Jeedom
* **Version du Plugin (ex: 2.6.0)**:La dernière
* **Type de modem**: Carteelectronique USB 1 compteur
* **Compteur linky**: en mode Historique
- [X] Oui 
- [ ] Non

* **Mode du compteur**:

## Logs
Merci de joindre les logs TELEINFO
Terminating...
Traceback (most recent call last):
  File "/usr/share/nginx/www/jeedom/plugins/teleinfo/ressources/teleinfo.py", line 453, in <module>
    teleinfo.run()
  File "/usr/share/nginx/www/jeedom/plugins/teleinfo/ressources/teleinfo.py", line 310, in run
    frameCsv = self.read()
  File "/usr/share/nginx/www/jeedom/plugins/teleinfo/ressources/teleinfo.py", line 191, in read
    resp = self._ser.readline()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 453, in read
    buf = os.read(self.fd, size-len(read))
OSError: [Errno 11] Resource temporarily unavailable
Terminating...
/bin/sh: 1: Syntax error: Unterminated quoted string
Terminating...

Merci pour votre support.

**Comment by ticed35** [comment]
Salut, par hasard as-tu coché le mode linky sur le plugin ? 
En mode historique il ne faut pas l'activer.
