### ISSUE TITLE
Stats quotidiennes à 0 + NOK

### ISSUE THREAD

**Issue by llaumgui** [NextDom/plugin-teleinfo#54]
## Description
J'ai des statistiques quotidiennes à 0 et des NOK sur la santé: 
![screenshot_2018-08-20 panel - jeedom](https://user-images.githubusercontent.com/411360/44352353-6d4aa380-a4a4-11e8-9963-2d24ad61c023.png)

Bien entendu, j'ai re-sauvé mon équipement et attendu 24H comme écrit dans la documentation.

## Etapes à reproduire (pour les bugs)
1. Aller sur le panel.
2. Afficher la santé.

## Contexte
RAS.

## Environnement
* **Version Jeedom**: 3.2.11
* **Platform**: DIY / Debian 9 / PHP 7.0.30-0+deb9u1 / MariaDB 10.1.26-MariaDB-0+deb9u1
* **Version du Plugin (ex: 2.6.0)**:  3.1.0 / 2018-05-15 01:53:58 
* **Type de modem**: USB
* **Compteur linky**: 
- [ ] Oui 
- [X] Non

* **Mode du compteur**: 1 compteur

## Logs
RAS.

**Comment by ak-enad** [comment]
@llaumgui, pour résoudre ce problème :

https://www.jeedom.com/forum/viewtopic.php?f=149&t=39461&p=654761#p654761

akenad :)

**Comment by ColonelMoutarde** [comment]
Salut, faites des pr et on regarde chaque cas 😀

**Comment by ticed35** [comment]
Correction présente dans le commit : https://github.com/NextDom/plugin-teleinfo/commit/f5ee26ff815b892273dd859cb8136a5e60bacbe1
Sera disponible en version stable 4.*.*
