### ISSUE TITLE
Plantage de jeedom

### ISSUE THREAD

**Issue by mika-nt28** [NextDom/plugin-teleinfo#56]
## Description
Au bout de quelques minute apres l'activation du plugin, j'ai un plantage de la bas sql
Avant ca tout se passe correctement
## Environnement
* **Version Jeedom**: 3.2.11
* **Platform**: Debian x64
* **Version du Plugin (ex: 2.6.0)**: 3.1.0 (2018-05-15 01:53:58)
* **Type de modem**: CarteElectronique
* **Compteur linky**: Non

> [Tue Sep 18 14:42:59.842388 2018] [:error] [pid 17226] [client 192.168.0.100:36674] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/core/class/DB.class.php:37
Stack trace:
#0 /var/www/html/core/class/DB.class.php(37): PDO->__construct('mysql:host=loca...', 'jeedom', '98cf71a1ab797b2', Array)
#1 /var/www/html/core/class/DB.class.php(49): DB->__construct()
#2 /var/www/html/core/class/DB.class.php(80): DB::getConnection()
#3 /var/www/html/core/class/config.class.php(144): DB::Prepare('SELECT `value`
...', Array, 0)
#4 /var/www/html/plugins/teleinfo/core/php/jeeTeleinfo.php(21): config::byKey('api')
#5 {main}
thrown in /var/www/html/core/class/DB.class.php on line 37

**Comment by mika-nt28** [comment]
il y a également une charge importante du processeur (30%) lors du démarrage du démon

**Comment by mika-nt28** [comment]
J'ai également régulièrement, mais je n'ai pas trouvé la sources

> /bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string

**Comment by mika-nt28** [comment]
Nouvelle erreur trouvé en lien directe avec la monté en charge

#python --version 
**Python 2.7.13**

`Exception in thread Thread-222:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 1073, in run
self.function(*self.args, **self.kwargs)
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 284, in timer_callback
if self.process.poll() is None:
AttributeError: 'NoneType' object has no attribute 'poll'
Exception in thread Thread-232:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 1073, in run
self.function(*self.args, **self.kwargs)
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 284, in timer_callback
if self.process.poll() is None:
AttributeError: 'NoneType' object has no attribute 'poll'
Exception in thread Thread-230:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 1073, in run
self.function(*self.args, **self.kwargs)
File "/var/www/html/plugins/teleinfo/ressources/teleinfo.py", line 284, in timer_callback
if self.process.poll() is None:`

**Comment by ticed35** [comment]
Salut @mika-nt28, ton compteur envoi t'il plus de données depuis quelques temps ? 
Il faudrait peu être ajouter une tempo sur l'envoi mais j'ai peur que cela fasse perdre des infos.

**Comment by ColonelMoutarde** [comment]
salut, @mika-nt28 ne veux plus être associé à nextdom. je ne pense pas qu'il te réponde

**Comment by ticed35** [comment]
Merci de l'info @ColonelMoutarde

**Comment by mika-nt28** [comment]
mon compteur a été changer et lorsque le plugin est actif je recois des donné lorsqu'il est actif.


@ColonelMoutarde je ne veux pas etre associé a cette organisation, ce qui ne m'empeche pas de repondre et de deposé des requette lorsque je vois un bug sur un plugin du market

**Comment by ColonelMoutarde** [comment]
@mika-nt28 super. Je suis content que tu t'occupe de ce plugin. 
Juste pour information, nous allons bientôt proposer un fork de jeedom. On cherche des béta testeurs.

**Comment by ticed35** [comment]
Version 4.0.0 devrait corriger le problème. 
https://github.com/NextDom/plugin-teleinfo/commit/0111d716f10cb2540bf3fe432e3018b0af2b072e
Rouvrir en cas d'issue toujours présente.
