### ISSUE TITLE
Bug lors de la création automatique d'un compteur

### ISSUE THREAD

**Issue by spyjo** [NextDom/plugin-teleinfo#67]
Bonjour,

J'ai rencontré une erreur PHP lors de la reconnaissance/création automatique du compteur qui était branché:

[Tue Mar 05 22:11:50.085610 2019] [:error] [pid 2123] [client 127.0.0.1:50490] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to teleinfo::createFromDef() must be of the type string, array given, called in /var/www/html/plugins/teleinfo/core/php/jeeTeleinfo.php on line 155 and defined in /var/www/html/plugins/teleinfo/core/class/teleinfo.class.php:62

Je pense que le soucis vient du fait que dans le code cela devrait être $data['device'] au lieu de $result['device'] dans la ligne ci-dessous, de mon coté j'ai modifié comme cela la variable et le compteur a bien été créé après.

https://github.com/NextDom/plugin-teleinfo/blob/59f74d1c0e70aa7280a16a1edee21576285acd79/core/php/jeeTeleinfo.php#L155

**Comment by ticed35** [comment]
Salut @spyjo, merci pour la recherche. 
J'ai mis la correction dans la prochaine version.
