### ISSUE TITLE
Affichage d index

### ISSUE THREAD

**Issue by Cogez** [NextDom/plugin-teleinfo#69]
## Description
Serais t il possible d avoir les index en Kwh
## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**:3
* **Raspberry Pi**:
* **Version du Plugin (ex: 2.6.0)**:4.1.2
* **Type de modem**: usb cartelectronic 1 TIC
* **Compteur linky**: oui
- [x] Oui 
- [ ] Non

## Logs
Merci de joindre les logs.

**Comment by ticed35** [comment]
Salut, les index sont affichés en kWh sur le panel. Pour ce qui est du dashboard je t'invite a utiliser un widget qui s'occupe de mettre en forme l'affichage.
