### ISSUE TITLE
Plus de données du Linky depuis la MAJ 4.2.2

### ISSUE THREAD

**Issue by StepG38** [NextDom/plugin-teleinfo#78]
## Description
Bonjour,
Je viens de faire la MAJ 4.2.2 et je ne reçois plus les données de mon linky.
J'ai 3 compteurs : 2 SAGEM S20C2 + 1 Linky tri SAGEMCOM S34C3
1 Panneaux photovoltaique + 1 Pompe à chaleur sur un modem carte electronique USB 2 compteurs 
1 compteur Linky en TIC Historique avec un modem carte electronique 1 compteur.
Avant la MAJ tout fonctionné avec V3.1.0 je crois
Les 2 compteurs SAGEM fonctionnent mais pas de données du linky !
Merci par avance de votre aide
Stéphane
## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Contexte
Le statut du Demon est "NOK"

## Environnement
* **Version Jeedom**: 3.3.19
* **Platform**: RPI
* **Version du Plugin (ex: 2.6.0)**: 4.2.2
* **Type de modem**: 2 Sagem + 1 Linky en tri
* **Compteur linky**: Oui
- [X ] Oui 
- [ ] Non

* **Mode du compteur**:
TIC Historique
## Logs
Merci de joindre les logs. 

TELEINFO
[2019-03-24 08:54:18][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement
[2019-03-24 08:54:30][ERROR] : Impossible de lancer le démon téléinfo, vérifiez la configuration.
[2019-03-24 08:54:42][ERROR] : [Production] Impossible de lancer le démon téléinfo, vérifiez la configuration
[2019-03-24 08:55:04][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement
[2019-03-24 08:55:16][ERROR] : Impossible de lancer le démon téléinfo, vérifiez la configuration.
[2019-03-24 08:55:29][ERROR] : [Production] Impossible de lancer le démon téléinfo, vérifiez la configuration

TELEINFO_DEAMON
Error: importing module from jeedom folder
No module named requests
Error: importing module from jeedom folder
No module named requests
Error: importing module from jeedom folder
No module named requests
Error: importing module from jeedom folder
No module named requests

**Comment by ticed35** [comment]
Salut, tu as un problème d'une librairie des dépendances qui n'est pas installée. Il s'agit de la requests. Les dépendances doivent l'installer au travers pip. Sinon cela doit être qqch comme : pip install requests

**Comment by StepG38** [comment]
Hello
Merci pour ton aide mais je ne comprends pas vraiment quoi faire pour
résoudre mon problème
Si tu peux m'expliquer !
Bien cordialement
Stéphane

**Comment by ticed35** [comment]
As tu réinstallé les dépendances ? Peux tu mettres les logs.

**Comment by StepG38** [comment]
Hello
Oui j'ai relancé les dépendances.
Pour les logs je les ai mis dans mon message
Merci
Stéphane

**Comment by ticed35** [comment]
Salut @StepG38, je ne vois pas les logs de l'installation des dépendances dans le message.

**Comment by StepG38** [comment]
Hello
J'ai mis les logs du plugin de mémoire.
De quels logs as tu besoin et comment les récupérer ?
Merci pour ton aide
Stéphane

**Comment by ticed35** [comment]
Il y a un fichier de log teleinfo_update qui se créé lorsque les dépendances sont installées. Il est accessible depuis la page de configuration du plugin ou la page des logs jeedom.

**Comment by StepG38** [comment]
Salut Cédric,
OK je vois bien les logs Teleinfo_Update
Par contre j'ai restauré une sauvegarde pour revenir sur la version 3.1.0
du plugin qui fonctionne avec mes 3 compteurs.
J'ai tellement galéré pour que cela fonctionne !
Je vais attendre un peu pour la mise à jour !
Il me manque surtout le paramètre injection de mon linky. Mes je peux
encore m'en passer.
Par contre il faut peut être passer en TIC standard pour le récupérer ?
Merci encore pour ton aide ! je ferais peut être la MAJ pendant les
vacances de pâques tranquillement : j'aurait surement besoin de toi à ce
moment la.
A bientôt
Stéphane

**Comment by ticed35** [comment]
Salut, 
cela dépend de ton linky si il est en historique ou standard. 
Laisse moi savoir quand tu fais l'upgrade.

**Comment by StepG38** [comment]
Hello
Mon linky est en mode historique.
Il faut donc que je demande le passage en standard  pour avoir l'injection ?
Tu sais comment faire pour le passage en standard ?
Je te recontacte dès que je relance la maj !
Merci pour ton aide
Stéphane

**Comment by ticed35** [comment]
Il me semble que les informations de production ne sont envoyé qu'en mode standard oui.

**Comment by ferrader** [comment]
J'ai exactement le même problème. plus de données remontées sur la dernière version.

**Comment by ticed35** [comment]
Bonjour @ferrader, 
Peux tu ouvrir une issue et poster tes logs / infos dessus. 

Merci

**Comment by ticed35** [comment]
Salut, le plugin a tellement évolué depuis qu'il faudra tester avec et ré-ouvrir l'incident si il y a des problèmes. 
En attendant je clos.

**Comment by StepG38** [comment]
Hello
Ok
Merci
Stéphane
