### ISSUE TITLE
Erreur sur les champs stats de production

### ISSUE THREAD

**Issue by micromad** [NextDom/plugin-teleinfo#81]
## Description
(Desole mais tu vas me prendre pour un gros lourd @ticed35 ;) )

Les champs stat_today, stat_month, ... du compteur de production montrent les donnees du compteur de consommation

## Etapes à reproduire (pour les bugs)
1. Avoir un compteur de consommation 
2. Avoir un compteur de production
3. Afficher les statistiques des deux compteurs et comparer

## Environnement
* **Version Jeedom**: 3.3.19
* **Platform**: Raspbian Jessie
* **Version du Plugin (ex: 4.2.0)**: 4.3
* **Type de modem**: Cartelectronic
* **Compteur linky**: oui (consommation) et oui (production)
* **Compteur standard ou historique**: historique (consommation) et standard (production)

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

**Comment by ticed35** [comment]
Salut @micromad, pas de soucis. As-tu pu essayer avec la 4.3.2.alpha ? J'ai effectué des corrections a ce niveau. Si tu vas sur la page option du plugin tu peux renseigner les index utilisés pour chaque type de compteur.

**Comment by micromad** [comment]
J'ai switche hier sur la branche master apres avoir fait le git pull.

Je teste la version develop ce soir et je te redis.

**Comment by ticed35** [comment]
Salut @micromad,
Je ne sais pas encore si je dois les déclarer pour le mois et l'année car je me dit qu'il est possible de faire un groupement de stat du jour afin d'avoir ces informations. 

C'est une bonne réflexion concernant les type de compteur. Je me dis qu'il faut tout de même garder l'identification (standard/historique) au niveau configuration car la définition linky change la vitesse de communication. Ou alors faire une fonction de détection du type de compteur :)

Il resterait donc à indiquer sur l'objet le mode production/consommation. Peux-t-on avoir de la consommation et injection sur le même compteur ? Si non alors il serait possible d'utiliser l'information de contrat pour automatiquement définir le type.

**Comment by micromad** [comment]
Salut @ticed35 

> Je ne sais pas encore si je dois les déclarer pour le mois et l'année car je me dit qu'il est possible de faire un groupement de stat du jour afin d'avoir ces informations.

Je comprends mais comme je te le disais sur l'architecture, j'ai peur que tu te compliques la vie : pourquoi ne pas voir le compteur de production comme un deuxieme compteur independant. Finalement le compteur de production n'est qu'un compteur en mode standard qui renvoie des champs en plus (cf le document EDF teleinformation).
Tu pourrais donc ecrire une classe compteur, ensuite des classes historique/standard qui heritent de compteur pour gerer les champs differents.
Avec cet architecture tu ecris les methodes de stats jour, mois, ... seulement la classe compteur qui prend en argument le champ qui fait le compteur (EJPHN, EJPHPM, EAIT....).

Et tu ne regroupes les informations seulement que pour l'affichage du panel, voir je me demande meme si tu es oblige de calculer les stats directements et si tu ne pourrais pas les calculer directement a l'affichage.

> 
> C'est une bonne réflexion concernant les type de compteur. Je me dis qu'il faut tout de même garder l'identification (standard/historique) au niveau configuration car la définition linky change la vitesse de communication. Ou alors faire une fonction de détection du type de compteur :)

En effet c'est un bon point. Mais il faudrait le detecter a la creation en testant les parametres historique et/ou standard avec une interception d'erreur si la lecture des champs echoue ?
Une autre maniere : il me semble que c'est indique sur l'ecran du Linky quand tu appuies sur les boutons --> A mettre dans une page d'aide "bulle" comme tu le fais
> 
> Il resterait donc à indiquer sur l'objet le mode production/consommation. Peux-t-on avoir de la consommation et injection sur le même compteur ? Si non alors il serait possible d'utiliser l'information de contrat pour automatiquement définir le type.

Perso je ne pense pas... Par contre je ne connais pas le cas de l'autoconsommation. Je pense tout de meme que deux compteurs soient necessaires (A verifier) mais c'est un cas a prendre en compte car les champs de stats seront differents : il faudra prevoir consommation (reseau), production (surplus injecte au reseau) et autoconmmation.

Par contre tu peux facilement tester un compteur en mode production/conso en regardant les champs qu'ils renvoient (voir si l'abonnement est triphase) en te conformant aux directives du document EDF comme ecis ci-dessus.

Desole ca fait un peu "inspecteur des travaux finis" mes commentaires mais je ne peux pas m'investir et t'aider dans l'ecriture du code par manque de temps (et aussi un peu car je fais du code toute la journee ;) ) 

@+

**Comment by ticed35** [comment]
Salut @micromad, merci pour les pistes. J'ai regardé ce qui était faisable et ai pu séparer certains trucs mais pas jusqu'à créer de nouvelles classes, pas la motivation. J'ai commencé à scinder tout ce qui est relatif aux compteurs maintenant j'ai 2 compteurs disponibles et peuvent être n'importe quel type. Il est possible de faire détecter le type de compteur par le plugin afin que les réglages se fassent automatiquement (sauf pour le cartelectronique 2 compteurs). Le type consommation / production est détecté directement par la donnée envoyée par le compteur donc plus besoin de renseigner l'abonnement. 
Au niveau des stats je suis obligé de les calculer afin d'avoir un historique mais il est possible d'améliorer tout ça tout de même.

**Comment by micromad** [comment]
Un grand merci @ticed35, du bon boulot !!!

J'ai une question un peu hors sujet: je viens de remarquer que depuis le 22 Mars (et certainement une mise a jour), les champs du plugin teleinfo ne sont plus moyennes en frequence horaire dans la base historyArch de Jeedom mais enregistres toutes les 3s.  
Comme il y a plusieurs mise a jour du core, pourrais-tu me confirmer que tu as le meme bug et que cela vient du plugin ? J'ai l'impression que les autres plugins font bien leur job. Ma base de donnee est en train d'exploser et Jeedom n'est plus capable pour certains champs de faire les graphs.

Si tel est le cas, j'ouvrirai un issue !!!

Encore merci @ticed35

**Comment by ticed35** [comment]
Hello @micromad, il s'agit du changement opéré sur les historiques afin de ne pas avoir de lissage en effet. Lors de l'enregistrement le lissage est supprimé des statistiques et index afin de ne pas avoir de valeurs erronées. 
Par contre toutes les 3 secondes cela ce produit genre pour les index et puissance mais le reste doit être plus lent non ?

**Comment by jmgfr** [comment]
Bonjour à tous.

J'utilise ce plugins depuis plusieurs mois / année, pour un compteur de consommation et un compteur de production.

Malgré les nombreuses mises à jour, j'ai toujours eu des erreurs de statistiques en activant l'historique sur le compteur de production:
Puissance de production cumulée avec celles de consommation, c'est l'erreur la plus fréquente.
Dans les paramétrages il y a une option pour ajouter un compteur de production, seul le port com diffère du compteur de production.
J'ai deux ports série de la même marque (ou plutôt noname),  aucune possibilité,  même avec avec des règles udev de s'assurer que le compteur de production et celui de consommation auront toujours le même port com après un redémarrage.
Les trames reçues par les deux ports com sont toujours associées au bon compteur grâce à la valeur ADCO.
Pourquoi le notion de "consommation", "production", "non-consommation", n'est pas définie au niveau du compteur ?
En résumé, dans les paramètres, il suffirait d'une option "ajouter un compteur", sans différentiation de consommation ou production, puis une fois le compteur créer, avoir la possibilité de définir en fonction de son identifiant (ADCO) de quel type de compteur il s'agit.
Ainsi lors du calcul des statistiques, c'est au niveau du compteur que le calcul "consommation", ou "production" est fait.
Je tente régulièrement de réactiver l'historique du compteur de production, mais, à chaque fois je me retrouve avec des stats faussées.
J'ai encore, à ce jour, désactiver tout historique sur le compteur de production afin d'éviter de mauvaises stats sur la consommation.
Aujourd'hui je n'effectue de stats que sur le compteur de conso, et pour la prod, j'ai un script qui envoie chaque nuit sur bdpv le relevé compteur de prod, c'est la seule solution qui m'est fonctionnelle.
Pour preuve j'avais fais une nouvelle tentative d'historisation de prod ces derniers jours, suite à la dernière maj mon historique de consmmation est descendu d'un coup (car nouveau calcul sans le compteur de production). Malheureusement les valeurs des jours précédents sont faussées et mon historique conso inclus la production.
![stat_teleinfo](https://user-images.githubusercontent.com/13685004/55743572-efd3a380-5a32-11e9-99c1-fbf368b2b530.PNG)
Merci,

**Comment by ticed35** [comment]
Salut @jmgfr, 
Tu peux définir les étiquettes pour les différents type de compteurs depuis le panneau option du plugin. Pour ce qui est des stats depuis la version 4.3.2 tous les compteurs ont leurs propres stats. Es-tu sûr de fonctionner avec une version => 4.3.2 ?

**Comment by jmgfr** [comment]
@ticed35 , Merci pour cette réponse rapide, 
version jeedom 3.3.20 (j'envisage de passer à nextdom mais il me faut réaliser des tests hors production, ce que je ne peux me permettre actuellement), version téléinfo 4.4.0, (a l’heure actuelle, je ne sais quelle version j'avais avant la mise à jour de ce jour puisque j'avais bloquer les maj suite à ces problèmes de stats, je regarderai dans les backups s'il le faut). concernant les options je ne trouve rien pour définir à qui est le compteur "production" ou "consommation" .
![option téléinfo](https://user-images.githubusercontent.com/13685004/55747673-0ed73300-5a3d-11e9-87bd-ea38896be70f.PNG), 
PS: je comprends la difficulté et les efforts fournis pour rendre ce plugin efficace, surtout dans cette phase de transition ou certains ont un compteur historique et d'autres un linky.
Pour ma part je suis  encore en historique et refuserai le linky tant qu'il ne sera pas capable de faire à minima, ce que fait mon installation domotique (visu en temps réel, gestion de mes équipements en temps réels en fonctions de la consommation, et, le tout, sans envoyer de données à quiconque) !
merci,
Cordialement

**Comment by ticed35** [comment]
Salut @jmgfr, en fait ici tu peux définir les index qui sont utilisés pour la production afin d'avoir les stats qui se calculent tels quels. Cela permet d'avoir la différenciation sur le panel. Le type du compteur est automatiquement déduit par la trame NGTF qui affiche production quand c'est nécessaire. Je ne sais pas exactement ce qui s'affiche dans le cas du type historique. Vu que tous les compteurs sont séparés depuis quelques versions tu ne devrais pas avoir de soucis au niveau des calculs, chaque compteur sera indépendant.

**Comment by ticed35** [comment]
@jmgfr, tout est correct de ton côté ?

**Comment by jmgfr** [comment]
Bonjour, a tous.
Oui tout est Ok, pour moi.
Merci
