### ISSUE TITLE
Problème consommation dernière heure

### ISSUE THREAD

**Issue by Rapsody09** [NextDom/plugin-teleinfo#82]
## Description
J'ai mis à jour le plugin hier, et depuis la mise à jour la valeur de consommation moyenne sur la dernière heure reste à 0.

![image](https://user-images.githubusercontent.com/48986124/55069248-e38b3600-5083-11e9-8c0d-b1e239fe97f5.png)

![image](https://user-images.githubusercontent.com/48986124/55069277-f1d95200-5083-11e9-9b3e-7f0d27fa9769.png)

Quand je teste la commande elle me retourne zero, le reste semble pourtant bien fonctionner

## Etapes à reproduire (pour les bugs)
1. Créer une commande avec Conso moyenne dernière heure
2. Le resultat reste à zéro
3.
4.

## Environnement
* **Version Jeedom**: 3.0
* **Platform**: Pi Linux
* **Version du Plugin (ex: 4.2.0)**:  4.3.0
* **Type de modem**: 
![image](https://user-images.githubusercontent.com/48986124/55069427-52688f00-5084-11e9-98bc-bf15b5c7c9d7.png)

* **Compteur linky**:
* **Compteur standard ou historique**:

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

**Comment by ticed35** [comment]
Salut @Rapsody09, peux-tu poster le fichier de log teleinfo pour voir ce qu'il se passe.
Merci

**Comment by ticed35** [comment]
Bug identifié, est corrigé dans la version 4.3.2 et disponible actuellement en beta. 
https://github.com/NextDom/plugin-teleinfo/commit/fe5daacbac4cf2e33e890e0c6a64d1f64d413a56

**Comment by Rapsody09** [comment]
Super merci pour la rapidité de correction :)

**Comment by bouboun59** [comment]
Bonjour, J'ai le même souci pour le calcul PAPP sur conso derniere minute
