### ISSUE TITLE
Pas de remontée d'info du cartelectronic suite à mise à jour plugin

### ISSUE THREAD

**Issue by GPGA** [NextDom/plugin-teleinfo#87]
## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**: 3.3.19 en mode stable

* **Platform**: Raspberry 3
* **Version du Plugin (ex: 4.2.0)**:  4.3.2
* **Type de modem**: carteelectronic 2 compteurs
* **Compteur linky**:
* **Compteur standard ou historique**: 

![Croquis (14)](https://user-images.githubusercontent.com/49324519/55656515-769c3c80-57f7-11e9-8d7a-48acc01c70b5.png)
![Croquis (15)](https://user-images.githubusercontent.com/49324519/55656516-769c3c80-57f7-11e9-933c-df05a07c92a8.png)

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

**Comment by luckymoi** [comment]
Je confirme le pb de fonctionnement depuis la maj 4.3.2

**Comment by ticed35** [comment]
Salut vous 2. 
Apparament vous fonctionnez sous la même version de ftdi que titi donc ce n'est pas un problème de dépendances. 
Est ce que dans un premier temps l'un d'entre vous pourrait me fournir un accès ssh à sa machine afin de tester le démon en direct. J'aurais besoin également de l'accès à l'interface jeedom pour contrôler le démon lors des test.  (En mp).
Merci

**Comment by GPGA** [comment]
Comment je fais pour te connecter en MP

**Comment by ticed35** [comment]
Hello @GPGA, tu peux m'envoyer par courriel ou sur le forum :)

**Comment by ticed35** [comment]
Salut @GPGA, @luckymoi, 
Le bug a été identifié et corrigé en version 4.4.0.
Pouvez-vous me faire un retour. 
Merci
Tag commit : https://github.com/NextDom/plugin-teleinfo/commit/fa60a49da26585e310d6814c14812b5cf989ab41

**Comment by ticed35** [comment]
Hello les gars, tout est correct dans la nouvelle version ? 
Merci

**Comment by GPGA** [comment]
Tout est redevenu dans l'ordre

⁣Envoyé par BlueMail ​

Le 11 avr. 2019 à 13:37, à 13:37, "Cédric" <notifications@github.com> a écrit:

**Comment by ticed35** [comment]
Merci

**Comment by luckymoi** [comment]
Bonsoir,

J'ai fait la maj et je confirme que cela semble fonctionner.

Merci,
