### ISSUE TITLE
Librairie setuptools manquante

### ISSUE THREAD

**Issue by antiff** [NextDom/plugin-teleinfo#90]
## Description
1ere installation : Impossible de lancer le démon Téléinfo
Le diagnostic n'indique rien de spécial
Résolu avec : pip install setuptools

## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**:
* **Platform**:
* **Version du Plugin (ex: 4.2.0)**:
* **Type de modem**:
* **Compteur linky**:
* **Compteur standard ou historique**:

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

**Comment by ticed35** [comment]
C'est fait, merci
