### ISSUE TITLE
Passage en mode standard Linky --> depuis failed

### ISSUE THREAD

**Issue by StephaneM74** [NextDom/plugin-teleinfo#91]
## Description
Suite au passage du linky en standard cette nuit, pas de compteur qui remonte
j'était en historique avant, c'etait ok
j'ai supprimé le plugin, reinstallé 
## Etapes à reproduire (pour les bugs)
1. le demon démarre mais pas de données
2.
3.
4.

## Contexte
Activation cette nuit du mode standard du Linky
en historique, tout était ok
## Environnement
* **Version Jeedom**: 3.3.20
* **Platform**: Smart
* **Version du Plugin (ex: 4.2.0)**:4.4.0
* **Type de modem**: GCE Electronis USB
* **Compteur linky**: Oui
* **Compteur standard ou historique**: Standard

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

[teleinfo.log](https://github.com/NextDom/plugin-teleinfo/files/3073071/teleinfo.log)
[teleinfo_deamon_conso.log](https://github.com/NextDom/plugin-teleinfo/files/3073072/teleinfo_deamon_conso.log)
[teleinfo_update.log](https://github.com/NextDom/plugin-teleinfo/files/3073073/teleinfo_update.log)

**Comment by ticed35** [comment]
Salut, je pense que ton modem n'a pas aimé le passage en mode standard. Peux tu essayer de le faire fonctionner avec le logiciel du fabriquant. 

Merci

**Comment by ticed35** [comment]
Salut @StephaneM74, des nouvelles ?

**Comment by StephaneM74** [comment]
Bonjour
désolé, j’étais parti en weekend :)
depuis le passage en mode standard, j'ai plusieurs soucis avec les trames du Linky
Mon gestionnaire de chauffage, qui est aussi raccordé sur le Linky est en erreur
j'ai donc mis le modem dans mon Pc et lu avec putty
les trames ne ressemblent à rien
j'ai donc contacté le fournisseur du modem, pas de réponse actuellement
j'ai au edf, puis enedis, surtout pour mon pb de gestionnaire de chauffage (qui gère aussi mon eau chaude) 
D’après eux, le mode standard du linky n'est pas compatible avec le gestionnaire de chauffage, je n'y crois pas
j'ai demandé aussi au fournisseur du gestionnaire de chauffage, delta core, mais pas de nouvelle

je pense que le linky envoie n'importe quoi dans le TIC, d’où les soucis
je vais peut être revenir en mode historique, mais ça m’embête, je voulais récupérer le compteur de ma production solaire
je te tiens au courant
Stéphane

**Comment by ticed35** [comment]
@StephaneM74, par hasard la vitesse de communication de tes appareils a t'elle été mise à jour ? le linky standard requiers 9600 et plus 1200.

**Comment by StephaneM74** [comment]
mon gestionnaire de chauffage indique un Def7, ce qui est bien un pb de communication avec le compteur
aucune idée de comment changer cela, j'attends la réponse de l'assistance de delta core
par contre, coté jeedom et le modem, aucune idée

**Comment by ticed35** [comment]
@StephaneM74, côté jeedom tu as le bouton de détection automatique du type mais si ton gestionnaire a de la difficulté c'est qu'il y a vraiment qqch côté compteur.

**Comment by StephaneM74** [comment]
je viens d'avoir différentes réponses :
 - coté gestionnaire de chauffage, les modules Delta Dore ne sont pas compatibles et il n'existe pas de modèle compatible :(
 - coté Modem USB de chez GCE-electronics, il n'est pas compatible avec le linky en mode standard, les nouveaux modèle le sont

Bref, j'ai demandé un retour arrière chez EDF, revenir en mode historique
c'est dommage, je souhaite lire le compteur indiquant la production solaire
merci pour tes efforts
Stéphane

**Comment by ticed35** [comment]
En effet c'est dommage, espérons qu'ils augmentent la compatibilité dans le futur.
