### ISSUE TITLE
pb de remonté des info suite a maj plugins

### ISSUE THREAD

**Issue by Esso1-jeedom** [NextDom/plugin-teleinfo#92]
suite a la mise a jour du plugin
je n'ai que 1 remonté d'info aprés plus rien ne remonte.
je suis repasser a l'ancienne version pour garder la remonté d'info

je suis sous Z83  
debian
NEXTDOM 0.1.4

**Comment by ticed35** [comment]
Sans aucune info ça va être compliqué ...

**Comment by Esso1-jeedom** [comment]
dit moi ce que tu veux en info . 
l'avant dernier versions remonte bien les infos et ce mets a jours, la dernière remonte 1 info et ne remonte rien ensuite. 
peut être voir avec l’équipe de Nextdom qui connait ce bug, j'avais posté sur leur forum .

**Comment by ticed35** [comment]
@Esso1-jeedom il me faudrait le package de diagnostique :)

**Comment by ticed35** [comment]
Suite à discution il s'agit en faite du problème de communication du wifinfo : 
https://www.jeedom.com/forum/viewtopic.php?p=705158#p705158
