### ISSUE TITLE
Error 500 depuis passage sur Linky

### ISSUE THREAD

**Issue by Clingo77** [NextDom/plugin-teleinfo#93]
## Description
Mon compteur vient d'ête changé pour un Linky. Il est en mode historique, je n'ai donc rian changé dans la config du plugin. J'ai réinstallé les dépendances et même le plugin sans succès.
Je vois bien les données remonter dans les log Teleinfo mais j'ai l'erreur suivante en boucle dans le log teleinfo_deamon_conso : Error on send request to jeedom, return code 500

Merci pour votre aide

[teleinfo_update.txt](https://github.com/NextDom/plugin-teleinfo/files/3079875/teleinfo_update.txt)
[teleinfo.txt](https://github.com/NextDom/plugin-teleinfo/files/3079876/teleinfo.txt)
[teleinfo_deamon_conso.txt](https://github.com/NextDom/plugin-teleinfo/files/3079877/teleinfo_deamon_conso.txt)

## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**: 3.3.20
* **Platform**: Linux Debian / NUC / Proxmox
* **Version du Plugin (ex: 4.2.0)**: 4.4.0
* **Type de modem**: Cartelectonic USB
* **Compteur linky**: oui
* **Compteur standard ou historique**: Historique

## Logs
Merci de joindre les fichiers de logs (Bouton télécharger en haut à droite sur Jeedom).

**Comment by ticed35** [comment]
Salut, peux tu également uploader le fichier http.error du même timestamp.
Merci

**Comment by Clingo77** [comment]
Salut ticed35, peux tu me dire où se trouve ces fichiers ?

**Comment by ticed35** [comment]
Onglet Analyse/Logs tu le trouveras dans la liste sur la gauche.

**Comment by Clingo77** [comment]
le voici ...
[httperror.txt](https://github.com/NextDom/plugin-teleinfo/files/3080672/httperror.txt)

**Comment by ticed35** [comment]
Je ne vois pas grand chose la dessus. Par hasard as-tu 2 objets avec le même identifiant compteur ?

**Comment by Clingo77** [comment]
Non je n'ai qu'un seul compteur

**Comment by ticed35** [comment]
Pourtant dans les logs je vois 2 objets : 
Compteur EDF OLD et Compteur

**Comment by Clingo77** [comment]
Exact, j'ai crée Compteur pour voir si le pb venait de là, mais cela n'a rien changé et je l'ai supprimé depuis

**Comment by Clingo77** [comment]
C'est bon j'ai trouvé le problème, j'ai du corriger l'identifiant du compteur qui n'était plus bon. Ce qui est étrange c'est que quand j'ai créé un nouveau compteur pour tester (et désactiver l'ancien) le numéro ne s'est pas renseigné tout seul, il me semblait que c'était le cas. 
En tout cas merci pour ton aide qui m'a mis sur la piste et désolé pour le dérangement ! :)

**Comment by Clingo77** [comment]
Pb résolu en rectifiant l'identifiant du compteur

**Comment by emerout** [comment]
@Clingo77 J'ai le même problème avec le changement de compteur pour un linky.
Comment vérifier et corriger l'identifiant de compteur ?
