### ISSUE TITLE
Problème sur plusieurs données depuis mise à jour

### ISSUE THREAD

**Issue by Rapsody09** [NextDom/plugin-teleinfo#96]
## Description

La moitié de mes compteurs ne fonctionnent plus depuis la dernière mise à jour, je ne comprends pas trop ce qu'il se passe.
J'ai notamment mes indicateurs :
- "Conso hier' basé sur la donnée : Conso totale hier, qui est figée depuis une dizaine de jours
- "Coût hier" basé sur la donnée : Conso totale hier ,qui est figée depuis une dizaine de jours
- "Coût mois" basé sur la donnée : Conso Moi en cours, qui est figée depuis une dizaine de jours

Et j'ai notamment une mention Obsolète qui est apparau sur plusieurs de mes indicateurs, sauf que je ne trouve pas de choix équivalent pour la remplacer.
Bref je n'ai plus grand chose qui fonctionne à part la consommation du jour ...

## Contexte

![Capture2](https://user-images.githubusercontent.com/48986124/56495225-65407900-64f5-11e9-9eb2-949338d776c7.PNG)
![Capture3](https://user-images.githubusercontent.com/48986124/56495228-696c9680-64f5-11e9-90e1-0040f83f8e09.PNG)

## Environnement
* **Version Jeedom**:  3.3.21
* **Platform**: Raspberry
* **Version du Plugin (ex: 4.2.0)**: 4.5.1
* **Type de modem**: 
* **Compteur linky**:

* **Compteur standard ou historique**:

## Logs
[teleinfo_deamon_conso.log](https://github.com/NextDom/plugin-teleinfo/files/3102943/teleinfo_deamon_conso.log)
[teleinfo_update.log](https://github.com/NextDom/plugin-teleinfo/files/3102946/teleinfo_update.log)

**Comment by Rapsody09** [comment]
Après quelques investigations supplémentaires j'ai cru comprendre que les stats mensuelles avaient été supprimées, mais je ne sais pas trop comment les remettre et si c'est possible ?
Par contre pour les stats de la veille je ne comprends pas, quand je vais dans la configuration de la commande elle me retourne toujours la valeur du 17/04/2019 alors que par exemple aujourd'hui on est le 24/04 ...

![Capture_stats_hier](https://user-images.githubusercontent.com/48986124/56636273-7fe72f00-6668-11e9-9eff-df08df884944.PNG)

**Comment by jmgfr** [comment]
Bonjour, 

Je viens de constater également, l'arrêt de mises à jour des stats mensuelles sur mon installation et ce, depuis la maj du 17-04.
Je vois rien dans le changelog, indiquant une éventuelle suppression de ces valeurs.
Ces informations étant importante pour moi, j'ai pour l'instant, restaurer le plugin depuis une sauvegarde faite avant le 17-04.

**Comment by ticed35** [comment]
Bonjour, 
C'est indiqué sur le changelog qu'en version 4.5.p

**Comment by ticed35** [comment]
Bonjour, c'est indiqué en changelog qu'en version 4.5.0 les stats ont été revus. 
Les stats sont renseignés dans les commandes STAT_YESTERDAY avec les commandes filles pour (HP/hc/Prod). Et d'autres comme STAT_TODAY.
Ils sont calculés toutes les nuits et renseignés dedans.
La méthode est différente d'un événement c'est le seul point que je pourrai possiblement changer pour que la donnée soit affiché.
Toutes les stats obsolètes ne sont plus calculés pour 2 raisons, cela faisait des redondances de calculs, utilisait beaucoup de ressources et il y avait facilement des erreurs de calculs qui pouvaient se glisser.
Il est possible d'accéder a toutes les infos de consommation lié a la teleinfo depuis le panel.
Pour faire d'autres suivi il existe d'autres plugins comme suivi conso par exemple.

Cédric

**Comment by Rapsody09** [comment]
Je ne comprends pas bien l'histoire d'affichage pour la commande STAT_YESTERDAY, pourquoi est-elle toujours affichée à la date du 17/04, il y a une manipulation à faire quelque part pour la mettre à jour ?

Personnellement j'avoue que les stats mensuelles étaient très utiles et si il avait été indiqué dans le changelog qu'elles étaient supprimées explicitement je n'aurai sans doute pas installé la nouvelle version car c'était la stat qui me semblait la plus intéressante. Mais je vais regarder cet autre plugin.

**Comment by ticed35** [comment]
Salut, 
Parce que je rentre les données historiques directement et je ne passe pas par un évènement Jeedom. 
Je peux changer cela. 
Pour le reste cela provoquait trop d'erreur de calcul donc il faut mieux s'appuyer sur d'autres traitements. 
Ton "coût" affichait seulement la valeur en wh ?

**Comment by Rapsody09** [comment]
Pour mon coût de la journée précédente j'utilise une simple formule de calcul dans ma commande : #value# / 1000 * 0.15 €
C'est approximatif mais ça me donne une idée du coût à la journée d'hier.

**Comment by ticed35** [comment]
@Rapsody09, 
si je te donne la possibilité de l'avoir sur le panel ?

**Comment by Rapsody09** [comment]
Merci @ticed35 , je suis preneur.  
Même si j'utilise principalement la version mobile avec un affichage simple de ce style (je n'ai pas trouvé comment afficher le panel en version mobile) :
![Capture](https://user-images.githubusercontent.com/48986124/57036328-4ad47100-6c54-11e9-9caa-0dbc12fb4b40.PNG)

**Comment by ticed35** [comment]
@Rapsody09, tu devrais pouvoir le refaire tout de même avec la mise à jour de la valeur sur la dernière version.
![image](https://user-images.githubusercontent.com/13416516/57074324-8b160c80-6cb1-11e9-8b7e-ea605fce3aaa.png)

**Comment by Rapsody09** [comment]
Genial, je confirme ça refonctionne ;-)
