### ISSUE TITLE
Absence de remontée dans Jeedom du module téléinfo

### ISSUE THREAD

**Issue by supa86** [NextDom/plugin-teleinfo#98]
## Description
Je n'ai plus de remontée du module téléinfo depuis quelques semaines maintenant
J'ai supprimé le compteur dans jeedom qui ne se mettait plus à jour
La création automatique ne se fait pas
Le diagnostique se déroule sans erreur
J'ai crée une VM avec un jeedom vierge et uniquement le plugin téléinfo mais sans succès
## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement ESXI 6.0
* **Version Jeedom**: V3.3.24
* **Platform**:  debian release 9.8 (stretch)
* **Version du Plugin (ex: 4.2.0)**: 4.5.1
* **Type de modem**: GCE Electronics USB
* **Compteur linky**: Non
* **Compteur standard ou historique**: Historique

## Logs
Merci de joindre les fichiers de logs où bien directement le package du diagnostique.

[teleinfo.zip](https://github.com/NextDom/plugin-teleinfo/files/3144734/teleinfo.zip)

**Comment by ticed35** [comment]
Salut, le package de logs contient des informations de début avril. Est-ce le bon ?

**Comment by supa86** [comment]
Salut,
Voici un diag fraîchement fait de ce matin.
J'ai du repasser mon Jeedom en 3.3.22 pour récupérer ma configuration html personalisée de certaines commandes car la 3.3.24 n'y donne plus accès.
[teleinfo.zip](https://github.com/NextDom/plugin-teleinfo/files/3145191/teleinfo.zip)

**Comment by ticed35** [comment]
Salut, en effet j'ai eu le même inconvénient avec les personnalisations html ^^.
Je vois que oui tout se lance bien par contre aucune info en provenance du modem.
Le modem remonte-il des informations avec le programme du fabriquant ? 
Il faudra que je me connecte pour regarder plus en détail sinon. Pour les accès on verra par courriel ;)

**Comment by supa86** [comment]
Salut,
je ne trouve pas de programme fabriquant pour la lecture des données mais juste pour lire l'eeprom et la flasher.
As-tu un lien?
par contre en hyperterm, les données se mettent bien à jour

**Comment by ticed35** [comment]
Non il y a tellement de compteurs que j'ai pas ça. 
Quand tu parles de l'hyperterm qui affiche les données, sur quelle machine ?

**Comment by supa86** [comment]
teraterm sur windows
gtkterm sur linux
les 2 me remontent des trames qui ont l'air correctes enfin je pense (cf impecran sur le forum de Jeedom)
les IINST1-2 et 3 par exemple les valeurs changent

**Comment by supa86** [comment]
Bonsoir Ticed35,
quand crois-tu que l'on puisse convenir d'un moment pour la téléassistance? ;-)
Merci d'avance

**Comment by ticed35** [comment]
Salut, 
Tu peux m'envoyer par courriel les infos d'un compte de connexion à ton jeedom ainsi qu'un accès ssh afin de pouvoir lancer manuellement le démon. 
Merci

**Comment by ticed35** [comment]
@supa86, c'est possible ?

**Comment by supa86** [comment]
Salut,
Si tu n'y vois pas d'inconvénients, je préférerai un TeamViewer ou anydesk
et je te donnerai les accès a Jeedom et a la vm en ssh.
Dispo ce soir ?

**Comment by ticed35** [comment]
Salut, je n'ai pas suivi l'incident. est-il tjs présent ?

**Comment by supa86** [comment]
Bonsoir,
Excuses moi pour le retard, pas mal pris ces derniers temps.
Pour t'informer, j'ai fait changer le compteur, et plus aucune erreur
depuis.
Merci pour ton aide et ton plugin.

@ bientôt
