### ISSUE TITLE
Pas de remontée  ni de création de compteur

### ISSUE THREAD

**Issue by vdh053** [NextDom/plugin-teleinfo#99]
Bonjour,

Aucune donnée ne remonte dans les statistiques ou dans le compteur que j'ai créé manuellement.

J'ai installé le plugin Téléinfo. (version Jeedom3.0)
Configuré le modem : Serial => /dev/ttyS0  (Compteur Sagem)

Je vois en debug que certaines données sont lues mais rien ne remonte dans le compteur ou les stats.

[teleinfolog (1).zip](https://github.com/NextDom/plugin-teleinfo/files/3144834/teleinfolog.1.zip)

Merci pour votre aide

**Comment by ticed35** [comment]
Salut, 
je vois un problème lors de la lecture, soit ton modem téléinfo plante, soit un autre programme essai d'accéder au port et coupe la récupération de données.

**Comment by vdh053** [comment]
Salut 
Merci pour l'analyse. Comment être sûr que ça ne vient pas du compteur ? Je n'ai que jeedom dinstalle sur mon rpi. Comment savoir si un programme tiers essaie d accéder ?
Pour le modem, c'est du homemade (octo et deux résistances)

**Comment by vdh053** [comment]
C'est désormais OK. Problème de vitesse de port côté Rpi.

**Comment by ticed35** [comment]
Tant mieux, la création s'est bien déroulé ensuite ?
